### ISSUE TITLE
sp_BlitzFirst : StartTime timezone issue

### ISSUE THREAD

**Issue by Oleksandr-Kosariev** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1107] opened 2017-09-07 10:59 UTC
sp_BlitzFirst, line 676 (master):

 `      r.start_time AS StartTime,`

The **start_time** column in the **sys.dm_exec_requests** is of _datetime_ datatype. When it is inserted into #BlitzFirstResults.StartTime it becomes _detetimeoffset_ with '+0:00' time zone. If the server has a different timezone it saves wrong values. It can be fixed in the following way:

`  TODATETIMEOFFSET (r.start_time, DATEPART(TZOFFSET, SYSDATETIMEOFFSET())) AS StartTime,`

Tested in SQL Server 2012.

**Comment by BrentOzar** [comment] 2017-09-07 11:29
Is this a duplicate of #1106?

**Comment by Oleksandr-Kosariev** [comment] 2017-09-07 11:31
I think, there is more than one place in code with the same issue.

**Comment by BrentOzar** [comment] 2017-09-07 11:33
Gotcha. Let's not make an issue for every single line in the code, though. Feel free to add the details in the first issue. Thanks though!

**Comment by Oleksandr-Kosariev** [comment] 2017-09-07 11:34
Ok, no problem.

**Closed by BrentOzar** 2017-09-07 11:33 UTC
