### ISSUE TITLE
XML parsing error when running sp_BlitzIndex

### ISSUE THREAD

**Issue by KuldarAndares** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2533] opened 2020-08-17 10:54 UTC
**Version of the script**
sp_BlitzIndex(TM) v7.98 - August 08, 2020

**What is the current behavior?**
I get error:
Msg 50000, Level 16, State 1, Procedure sp_BlitzIndex, Line 1980 [Batch Start Line 0]
DB_name database failed to process. XML parsing: line 1, character 4000, unexpected end of input

**If the current behavior is a bug, please provide the steps to reproduce.**
I execute script from master:
EXEC sp_BlitzIndex @DatabaseName=N'DB_name'

From messages tab I can see:
Starting run. sp_BlitzIndex(TM) v7.98 - August 08, 2020
Create temp tables.
Adding UQ index on #IndexSanity (database_id, object_id, index_id)
Number of databases to examine: 1
Checking partition counts to exclude databases with over 100 partitions
Starting loop through databases

DB_name
Inserting data into #IndexColumns for clustered indexes and heaps
Inserting data into #IndexColumns for nonclustered indexes
Inserting data into #IndexSanity
Checking partition count
Preferring non-2012 syntax with LEFT JOIN to sys.dm_db_index_operational_stats
Inserting data into #IndexPartitionSanity
Warning: Null value is eliminated by an aggregate or other SET operation.
Inserting data into #MissingIndexes
Failure populating temp tables.
Last @dsql: SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;WITH ColumnNamesWithDataTypes AS(SELECT id.index_handle,id.object_id,cn.IndexColumnType,STUFF((SELECT cn_inner.ColumnName + ' ' +
					N' {' + CASE	 WHEN ty.name IN ( 'varchar', 'char' ) THEN ty.name + '(' + CASE WHEN co.max_length = -1 THEN 'max' ELSE CAST(co.max_length AS VARCHAR(25)) END + ')'
								WHEN ty.name IN ( 'nvarchar', 'nchar' ) THEN ty.name + '(' + CASE WHEN co.max_length = -1 THEN 'max' ELSE CAST(co.max_length / 2 AS VARCHAR(25)) END + ')'
								WHEN ty.name IN ( 'decimal', 'numeric' ) THEN ty.name + '(' + CAST(co.precision AS VARCHAR(25)) + ', ' + CAST(co.scale AS VARCHAR(25)) + ')'
								WHEN ty.name IN ( 'datetime2' ) THEN ty.name + '(' + CAST(co.scale AS VARCHAR(25)) + ')'
								ELSE ty.name END + '} '
				FROM	sys.dm_db_missing_index_details AS id_inner
				CROSS APPLY(
					SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Equality' AS IndexColumnType
					FROM	(VALUES (CONVERT(XML, '<x>' + REPLACE(id_inner.equality_columns, ',', '</x><x>')+'</x>'))) x(n)
					CROSS APPLY n.nodes('x') node(v)
				UNION ALL
					SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Inequality' AS IndexColumnType
					FROM	(VALUES (CONVERT(XML, '<x>' + REPLACE(id_inner.inequality_columns, ',', '</x><x>')+'</x>'))) x(n)
					CROSS APPLY n.nodes('x') node(v)
				UNION ALL
					SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Included' AS IndexColumnType
					FROM	(VALUES (CONVERT(XML, '<x>' + REPLACE(id_inner.included_columns, ',', '</x><x>')+'</x>'))) x(n)
					CROSS APPLY n.nodes('x') node(v)
			)AS cn_inner		JOIN	[DB_name].sys.columns AS co ON co.object_id = id_inner.object_id AND '[' + co.name + ']' = cn_inner.ColumnName
				JOIN	[DB_name].sys.types AS ty ON ty.user_type_id = co.user_type_id 
                WHERE id_inner.index_handle = id.index_handle
				AND	id_inner.object_id = id.object_id
				AND cn_inner.IndexColumnType = cn.Ind...
Msg 50000, Level 16, State 1, Procedure sp_BlitzIndex, Line 1980 [Batch Start Line 0]
DB_name database failed to process. XML parsing: line 1, character 4000, unexpected end of input

Completion time: 2020-08-17T13:16:05.4782632+03:00

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Version 14.0.1000.169 (Standard)
OS Windows Server 2019 Standard
It did work before I updated Blitz scripts. I don't know what version i had before.

**Comment by KuldarAndares** [comment] 2020-08-17 11:01
Only happens with one specific database.

**Comment by BrentOzar** [comment] 2020-08-17 11:06
Sorry to hear that, and thanks for the bug report. This sounds like it's coming from a new feature we added to show the datatypes of each missing index column name.

Can you try an older version of sp_BlitzIndex and use @Mode = 3, which will list out all of the missing indexes, and then look for ones that might be amazingly long, or have amazingly long column names, or unusual column names? That'll help us figure out what's going on. Thanks!

**Comment by KuldarAndares** [comment] 2020-08-17 11:42
I think that you're buddy Clippy is working really hard to get me as you're client. He recommends me to create index on one column with 257 included columns xD.
Example table structure:
CREATE TABLE [dbo].[Example](
	[AAAA001] [nchar](10) NOT NULL,
	[AAAA002] [nvarchar](35) NOT NULL,
	[AAAA003] [nvarchar](35) NOT NULL,
	[AAAA004] [nvarchar](35) NOT NULL,
	[AAAA005] [nvarchar](35) NOT NULL,
	[AAAA006] [nvarchar](35) NOT NULL,
	[AAAA007] [nvarchar](35) NOT NULL,
	[AAAA008] [nvarchar](35) NOT NULL,
	[AAAA009] [nvarchar](35) NOT NULL,
	[AAAA010] [nvarchar](4) NOT NULL,
	[AAAA011] [nvarchar](20) NOT NULL,
	[AAAA012] [nvarchar](10) NOT NULL,
	[AAAA013] [nvarchar](20) NOT NULL,
	[AAAA014] [nvarchar](1) NOT NULL,
	[AAAA015] [nvarchar](1) NOT NULL,
	[AAAA016] [numeric](14, 8) NOT NULL,
	[AAAA017] [nvarchar](120) NOT NULL,
	[AAAA018] [nvarchar](20) NOT NULL,
	[AAAA019] [nvarchar](2) NOT NULL,
	[AAAA020] [nvarchar](19) NOT NULL,
	[AAAA021] [nvarchar](20) NOT NULL,
	[AAAA022] [nvarchar](2) NOT NULL,
	[AAAA023] [nvarchar](3) NOT NULL,
	[AAAA024] [nvarchar](2) NOT NULL,
	[AAAA025] [nvarchar](1) NOT NULL,
	[AAAA026] [nvarchar](2) NOT NULL,
	[AAAA027] [nvarchar](2) NOT NULL,
	[AAAA028] [nvarchar](1) NOT NULL,
	[AAAA029] [nvarchar](2) NOT NULL,
	[AAAA030] [nvarchar](1) NOT NULL,
	[AAAA031] [nvarchar](1) NOT NULL,
	[AAAA032] [nvarchar](2) NOT NULL,
	[AAAA033] [nvarchar](1) NOT NULL,
	[AAAA034] [nvarchar](1) NOT NULL,
	[AAAA035] [nvarchar](3) NOT NULL,
	[AAAA036] [nvarchar](2) NOT NULL,
	[AAAA037] [numeric](28, 8) NOT NULL,
	[AAAA038] [numeric](28, 8) NOT NULL,
	[AAAA039] [numeric](28, 8) NOT NULL,
	[AAAA040] [numeric](28, 8) NOT NULL,
	[AAAA041] [numeric](28, 8) NOT NULL,
	[AAAA042] [numeric](28, 8) NOT NULL,
	[AAAA043] [numeric](28, 8) NOT NULL,
	[AAAA044] [numeric](28, 8) NOT NULL,
	[AAAA045] [numeric](28, 8) NOT NULL,
	[AAAA046] [int] NOT NULL,
	[AAAA047] [numeric](28, 8) NOT NULL,
	[AAAA048] [int] NOT NULL,
	[AAAA049] [nvarchar](4) NOT NULL,
	[AAAA050] [datetime] NOT NULL,
	[AAAA051] [datetime] NOT NULL,
	[AAAA052] [nvarchar](25) NOT NULL,
	[AAAA053] [nvarchar](25) NOT NULL,
	[AAAA054] [nvarchar](35) NOT NULL,
	[AAAA055] [nvarchar](3) NOT NULL,
	[AAAA056] [nvarchar](10) NOT NULL,
	[AAAA057] [numeric](28, 8) NOT NULL,
	[AAAA058] [numeric](28, 8) NOT NULL,
	[AAAA059] [nvarchar](1) NOT NULL,
	[AAAA060] [nvarchar](1) NOT NULL,
	[AAAA061] [nvarchar](1) NOT NULL,
	[AAAA062] [numeric](28, 8) NOT NULL,
	[AAAA063] [numeric](28, 8) NOT NULL,
	[AAAA064] [nvarchar](2) NOT NULL,
	[AAAA065] [nvarchar](3) NOT NULL,
	[AAAA066] [nvarchar](9) NOT NULL,
	[AAAA067] [nvarchar](1) NOT NULL,
	[AAAA068] [nvarchar](1) NOT NULL,
	[AAAA069] [nvarchar](2) NOT NULL,
	[AAAA070] [nvarchar](2) NOT NULL,
	[AAAA071] [nvarchar](4) NOT NULL,
	[AAAA072] [nvarchar](5) NOT NULL,
	[AAAA073] [nvarchar](1) NOT NULL,
	[AAAA074] [nvarchar](1) NOT NULL,
	[AAAA075] [nvarchar](1) NOT NULL,
	[AAAA076] [int] NOT NULL,
	[AAAA077] [nvarchar](2) NOT NULL,
	[AAAA078] [nvarchar](13) NOT NULL,
	[AAAA079] [nvarchar](35) NOT NULL,
	[AAAA080] [numeric](13, 8) NOT NULL,
	[AAAA081] [numeric](28, 8) NOT NULL,
	[AAAA082] [numeric](28, 8) NOT NULL,
	[AAAA083] [nvarchar](10) NOT NULL,
	[AAAA084] [nvarchar](10) NOT NULL,
	[AAAA085] [nvarchar](1) NOT NULL,
	[AAAA086] [nvarchar](2) NOT NULL,
	[AAAA087] [nvarchar](2) NOT NULL,
	[AAAA088] [numeric](28, 8) NOT NULL,
	[AAAA089] [numeric](28, 8) NOT NULL,
	[AAAA090] [numeric](28, 8) NOT NULL,
	[AAAA091] [numeric](28, 8) NOT NULL,
	[AAAA092] [nvarchar](16) NOT NULL,
	[AAAA093] [nvarchar](10) NOT NULL,
	[AAAA094] [nvarchar](34) NOT NULL,
	[AAAA095] [nvarchar](1) NOT NULL,
	[AAAA096] [nvarchar](1) NOT NULL,
	[AAAA097] [nvarchar](1) NOT NULL,
	[AAAA098] [nvarchar](6) NOT NULL,
	[AAAA099] [nvarchar](35) NOT NULL,
	[AAAA100] [nvarchar](6) NOT NULL,
	[AAAA101] [nvarchar](1) NOT NULL,
	[AAAA102] [nvarchar](1) NOT NULL,
	[AAAA103] [nvarchar](4) NOT NULL,
	[AAAA104] [nvarchar](3) NOT NULL,
	[AAAA105] [nvarchar](1) NOT NULL,
	[AAAA106] [nvarchar](10) NOT NULL,
	[AAAA107] [nvarchar](2) NOT NULL,
	[AAAA108] [nvarchar](2) NOT NULL,
	[AAAA109] [nvarchar](200) NOT NULL,
	[AAAA110] [nvarchar](1) NOT NULL,
	[AAAA111] [nvarchar](12) NOT NULL,
	[AAAA112] [nchar](2) NOT NULL,
	[AAAA113] [nchar](1) NOT NULL,
	[AAAA114] [nchar](1) NOT NULL,
	[AAAA115] [nchar](1) NOT NULL,
	[AAAA116] [nchar](4) NOT NULL,
	[AAAA117] [nchar](1) NOT NULL,
	[AAAA118] [nchar](1) NOT NULL,
	[AAAA119] [nchar](1) NOT NULL,
	[AAAA120] [int] NOT NULL,
	[AAAA121] [int] NOT NULL,
	[AAAA122] [int] NOT NULL,
	[AAAA123] [nvarchar](12) NOT NULL,
	[AAAA124] [int] NOT NULL,
	[AAAA125] [nvarchar](10) NOT NULL,
	[AAAA126] [nchar](10) NOT NULL,
	[AAAA127] [nchar](1) NOT NULL,
	[AAAA128] [nchar](1) NOT NULL,
	[AAAA129] [nvarchar](25) NOT NULL,
	[AAAA130] [int] NOT NULL,
	[AAAA131] [int] NOT NULL,
	[AAAA132] [datetime] NOT NULL,
	[AAAA133] [int] NOT NULL,
	[AAAA134] [int] NOT NULL,
	[AAAA135] [nchar](1) NOT NULL,
	[AAAA136] [int] NOT NULL,
	[AAAA137] [nchar](2) NOT NULL,
	[AAAA138] [int] NOT NULL,
	[AAAA139] [nchar](2) NOT NULL,
	[AAAA140] [nchar](1) NOT NULL,
	[AAAA141] [nchar](6) NOT NULL,
	[AAAA142] [nchar](1) NOT NULL,
	[AAAA143] [nchar](6) NOT NULL,
	[AAAA144] [nvarchar](10) NOT NULL,
	[AAAA145] [nvarchar](18) NOT NULL,
	[AAAA146] [nvarchar](20) NOT NULL,
	[AAAA147] [nvarchar](20) NOT NULL,
	[AAAA148] [nvarchar](20) NOT NULL,
	[AAAA149] [nvarchar](10) NOT NULL,
	[AAAA150] [nvarchar](10) NOT NULL,
	[AAAA151] [nvarchar](10) NOT NULL,
	[AAAA152] [nvarchar](10) NOT NULL,
	[AAAA153] [nvarchar](2) NOT NULL,
	[AAAA154] [nvarchar](1) NOT NULL,
	[AAAA155] [nvarchar](2) NOT NULL,
	[AAAA156] [nchar](6) NOT NULL,
	[AAAA157] [nchar](1) NOT NULL,
	[AAAA158] [int] NOT NULL,
	[AAAA159] [nvarchar](1) NOT NULL,
	[AAAA160] [nvarchar](1) NOT NULL,
	[AAAA161] [nchar](1) NOT NULL,
	[AAAA162] [int] NOT NULL,
	[AAAA163] [int] NOT NULL,
	[AAAA164] [nchar](2) NOT NULL,
	[AAAA165] [nchar](2) NOT NULL,
	[AAAA166] [nvarchar](4) NOT NULL,
	[AAAA167] [nvarchar](2) NOT NULL,
	[AAAA168] [nvarchar](6) NOT NULL,
	[AAAA169] [nvarchar](2) NOT NULL,
	[AAAA170] [nvarchar](2) NOT NULL,
	[AAAA171] [nvarchar](2) NOT NULL,
	[AAAA172] [nvarchar](1) NOT NULL,
	[AAAA173] [nvarchar](1) NOT NULL,
	[AAAA174] [int] NOT NULL,
	[AAAA175] [int] NOT NULL,
	[AAAA176] [int] NOT NULL,
	[AAAA177] [int] NOT NULL,
	[AAAA178] [nvarchar](1) NOT NULL,
	[AAAA179] [nchar](2) NOT NULL,
	[AAAA180] [nvarchar](6) NOT NULL,
	[AAAA181] [nchar](1) NOT NULL,
	[AAAA182] [nchar](1) NOT NULL,
	[AAAA183] [nvarchar](2) NOT NULL,
	[AAAA184] [nvarchar](2) NOT NULL,
	[AAAA185] [nvarchar](2) NOT NULL,
	[AAAA186] [nvarchar](25) NOT NULL,
	[AAAA187] [nvarchar](25) NOT NULL,
	[AAAA188] [nvarchar](25) NOT NULL,
	[AAAA189] [nvarchar](2) NOT NULL,
	[AAAA190] [nvarchar](10) NOT NULL,
	[AAAA191] [nvarchar](10) NOT NULL,
	[AAAA192] [nvarchar](10) NOT NULL,
	[AAAA193] [nvarchar](200) NOT NULL,
	[AAAA194] [nvarchar](35) NOT NULL,
	[AAAA195] [nvarchar](35) NOT NULL,
	[AAAA196] [nvarchar](35) NOT NULL,
	[AAAA197] [nvarchar](1) NOT NULL,
	[AAAA198] [nvarchar](150) NOT NULL,
	[AAAA199] [nvarchar](150) NOT NULL,
	[AAAA200] [nvarchar](150) NOT NULL,
	[AAAA201] [nvarchar](150) NOT NULL,
	[AAAA202] [nvarchar](150) NOT NULL,
	[AAAA203] [nvarchar](150) NOT NULL,
	[AAAA204] [nvarchar](150) NOT NULL,
	[AAAA205] [nvarchar](150) NOT NULL,
	[AAAA206] [nvarchar](150) NOT NULL,
	[AAAA207] [nvarchar](150) NOT NULL,
	[AAAA208] [nvarchar](150) NOT NULL,
	[AAAA209] [nvarchar](150) NOT NULL,
	[AAAA210] [nvarchar](150) NOT NULL,
	[AAAA211] [nvarchar](150) NOT NULL,
	[AAAA212] [nvarchar](150) NOT NULL,
	[AAAA213] [nvarchar](150) NOT NULL,
	[AAAA214] [nvarchar](150) NOT NULL,
	[AAAA215] [nvarchar](150) NOT NULL,
	[AAAA216] [nvarchar](150) NOT NULL,
	[AAAA217] [nvarchar](150) NOT NULL,
	[AAAA218] [nvarchar](1) NOT NULL,
	[AAAA219] [nchar](1) NOT NULL,
	[AAAA220] [datetime] NOT NULL,
	[AAAA221] [datetime] NOT NULL,
	[AAAA222] [nchar](1) NOT NULL,
	[AAAA223] [numeric](28, 8) NOT NULL,
	[AAAA224] [numeric](28, 8) NOT NULL,
	[AAAA225] [numeric](28, 8) NOT NULL,
	[AAAA226] [numeric](28, 8) NOT NULL,
	[AAAA227] [numeric](28, 8) NOT NULL,
	[AAAA228] [numeric](28, 8) NOT NULL,
	[AAAA229] [numeric](28, 8) NOT NULL,
	[AAAA230] [numeric](28, 8) NOT NULL,
	[AAAA231] [numeric](36, 8) NOT NULL,
	[AAAA232] [numeric](36, 8) NOT NULL,
	[AAAA233] [numeric](36, 8) NOT NULL,
	[AAAA234] [numeric](28, 8) NOT NULL,
	[AAAA235] [nvarchar](36) NOT NULL,
	[AAAA236] [nvarchar](10) NOT NULL,
	[AAAA237] [nvarchar](50) NOT NULL,
	[AAAA238] [nchar](1) NOT NULL,
	[AAAA239] [nvarchar](12) NOT NULL,
	[AAAA240] [nvarchar](15) NOT NULL,
	[AAAA241] [nvarchar](15) NOT NULL,
	[AAAA242] [nchar](2) NOT NULL,
	[AAAA243] [nchar](2) NOT NULL,
	[AAAA244] [nvarchar](12) NOT NULL,
	[AAAA245] [numeric](28, 8) NOT NULL,
	[AAAA246] [numeric](28, 8) NOT NULL,
	[AAAA247] [numeric](28, 8) NOT NULL,
	[AAAA248] [numeric](28, 8) NOT NULL,
	[AAAA249] [numeric](28, 8) NOT NULL,
	[AAAA250] [int] NOT NULL,
	[AAAA251] [numeric](28, 8) NOT NULL,
	[AAAA252] [numeric](28, 8) NOT NULL,
	[AAAA253] [int] NOT NULL,
	[AAAA254] [nchar](3) NOT NULL,
	[AAAA255] [nchar](1) NOT NULL,
	[AAAA256] [nvarchar](10) NOT NULL,
	[AAAA257] [nvarchar](34) NOT NULL,
	[AAAA258] [nchar](1) NOT NULL,
	[AAAA259] [nchar](1) NOT NULL,
 CONSTRAINT [Example1] PRIMARY KEY CLUSTERED 
(
	[AAAA001] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

**Comment by BrentOzar** [comment] 2020-08-17 11:48
HAHAHA, wow, that's epic. Okay, perfect, thanks - that'll help us figure out how to tone down what he's asking for.

**Comment by chrisgs100** [comment] 2020-08-25 03:26
Brent - thanks for pointing me over here with my query. This does seem to be the same probldem i am having. Using the consultant toolkit for the first time. Seem to be using the same (mostly) scripts. The sp_blitzindex component is giving me this error. I have made the changes in the 70_sp_BlitzIndex.sql file as outlined in the fix (had to adjust for line numbers a little). After running again, on the same points in the process i still get errors but now

13:21:56.8575 Info - Calling sqlData.ExecuteQuery to execute query 'sp_BlitzIndex Mode 3'
13:22:36.9139 Error - Source: .Net SqlClient Data Provider; Message: navision database failed to process. XML parsing: line 1, character 4004, illegal qualified name character;

I have double checked the changes and they look correct, just casting to NVARCHAR(MAX)
Chris

**Comment by gdoddsy** [comment] 2020-08-25 03:31
@chrisgs100 - that looks like the same bug. Brent took a pull request to fix it...kind of. It truncates some columns if they go over 4000.

I'm doing my paid job at the moment, but I think I have a fix for the create index script. Still trying to work out why the column list is truncated. Should have something in the next few days.

**Comment by gdoddsy** [comment] 2020-08-25 12:39
@BrentOzar - pull request submitted to fix the issues found in the live stream. Tested it out with the repro steps that I added on the weekend to that issue. Confirmed that the included columns with data type and the create index script are not truncated. I don't have the will power to write a where clause that will test out the equality and inequality columns, but they work with sane amounts of data (like 2 columns each).

1 final bug I did find, if you include a few of those massive columns then the name of the new index is > 128 characters, which SQL isn't a fan of. E.g.:
`CREATE INDEX Reputation_ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ15_CreationDate_ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ11 ON Samples.dbo.StackOverflowUsers (Reputation, ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ15, CreationDate, ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ11) `

If you try to run that, then SQL says ~you're an idiot~ `The identifier that starts with 'Reputation_ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ15_CreationDa' is too long. Maximum length is 128.`

I'm happy to truncate this, but not sure the best option. Depending on the columns, there's a good chance you'll end up with duplicate index name errors instead. Part of me thinks just leave it as it is and let it fail with a big red error and make it responsibility of the ~sucker~ poor soul trying to create an index on this table.

**Comment by BrentOzar** [comment] 2020-08-27 12:34
Nice work Greg! Merging the pull request into dev, will be in the September release with credit to you in the release notes.

**Closed by BrentOzar** 2020-08-27 12:34 UTC
Labels: bug, sp_BlitzIndex

**Comment by chrisgs100** [comment] 2020-08-28 00:36
Just so you know. I copied the changes into the 70_sp_BlitzIndex.sql file and ran the consultants toolkit on the same databases i had had the issue on and both worked fine
Thanks

**Comment by gdoddsy** [comment] 2020-08-28 00:38
@chrisgs100 - glad it worked.
