### ISSUE TITLE
sp_BlitzLock error - Name cannot begin with the ' ' character, hexadecimal value 0x20.

### ISSUE THREAD

**Issue by Sindric1** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3564] opened 2024-09-02 08:43 UTC
sp_BlitzLock 
@Version = '8.21', @VersionDate = '20240701';

SQL Server version 2019 CU27

Hello,
When running the stored procedure sp_BlitzLoc in SQL Server Management Studio, I am occasionally getting just the first table results and not the complete list as it stops in the middle. 
When I check the Messages Tab I see the error
 “Name cannot begin with the ' ' character, hexadecimal value 0x20.”
By Using the parameters @StartDate and @EndDate I have been able to identify the issue and further made a correction in my version of the stored procedure to fix the issue and provide all the results back.

I have added an extra REPLACE( , '?', '') arround this code:

UPDATE d
                SET d.inputbuf =
                        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                            d.inputbuf,
                        NCHAR(31), N'?'), NCHAR(30), N'?'), NCHAR(29), N'?'), NCHAR(28), N'?'), NCHAR(27), N'?'),
                        NCHAR(26), N'?'), NCHAR(25), N'?'), NCHAR(24), N'?'), NCHAR(23), N'?'), NCHAR(22), N'?'),
                        NCHAR(21), N'?'), NCHAR(20), N'?'), NCHAR(19), N'?'), NCHAR(18), N'?'), NCHAR(17), N'?'),
                        NCHAR(16), N'?'), NCHAR(15), N'?'), NCHAR(14), N'?'), NCHAR(12), N'?'), NCHAR(11), N'?'),
                        NCHAR(8),  N'?'),  NCHAR(7), N'?'),  NCHAR(6), N'?'),  NCHAR(5), N'?'),  NCHAR(4), N'?'),
                        NCHAR(3),  N'?'),  NCHAR(2), N'?'),  NCHAR(1), N'?'),  NCHAR(0), N'?')
            FROM #deadlocks AS d

I am not sure if this change has any negative affect anywhere else, but it dose solve my error.
Here is a copy of my sp with the change [sp_BlitzLock.txt](https://github.com/user-attachments/files/16834842/sp_BlitzLock.txt)

**Comment by BrentOzar** [comment] 2024-10-14 14:48
Hi! We don't take code changes via direct links - you'll need to contribute a pull request as described here:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

If you're new to Github, there are also instruction links on there with tutorials on how to do your first pull request. If you can't do that, no problem, let me know and I'll close the issue.

You might ask, "Brent, why don't you just take my changes?" The problem is that you're not the only person making changes, and by contributing a pull request, it makes it easy for us to merge your code with others, and see the exact changes you've made.

**Comment by BrentOzar** [comment] 2024-12-06 23:28
I haven't heard back from you in a couple of months, so I'm going to go ahead and close this for now, but if you want to submit a pull request feel free to. Thanks!

**Closed by BrentOzar** 2024-12-06 23:28 UTC
