### ISSUE TITLE
sp_Blitz - MSDB Backup History

### ISSUE THREAD

**Issue by Tom-Hogan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1059] opened 2017-08-07 14:18 UTC
When I run sp_Blitz I'm getting both _MSDB Backup History Not Purged_ (CheckID 3) and _MSDB Backup History Purged Too Frequently_ (CheckID 186) in my results which is contradictory.

I'm keeping my history for 45 days.  I think for CheckID 186 the order by on 

> SELECT TOP 1 backup_start_date FROM msdb.dbo.backupset ORDER BY 1 

should have a DESC there so you're comparing the the most recent backup instead of the oldest.

**Comment by BrentOzar** [comment] 2017-08-07 14:19
When you file an issue, make sure to search for existing issues first. Closing this one as a dupe of #1053. Thanks though!

**Closed by BrentOzar** 2017-08-07 14:19 UTC

**Comment by Tom-Hogan** [comment] 2017-08-07 17:24
My bad.  I only checked the open issues.
