### ISSUE TITLE
sp_BlitzFirst Bug

### ISSUE THREAD

**Issue by goforebroke** [BrentOzarULTD/SQL-Server-First-Responder-Kit#614] opened 2016-12-02 00:18 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Error when running sp_BlitzFirst

Setting up configuration variables
Msg 241, Level 16, State 1, Line 7
Conversion failed when converting date and/or time from character string.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com

Install sp_BlitzFirst and its dependency sp_BlitzWho

run the sql below  via a sql agent job per https://www.brentozar.com/askbrent/

EXEC sp_BlitzFirst 
  @OutputDatabaseName = 'DBAtools', --output to my custom db 
  @OutputSchemaName = 'dbo', 
  @OutputTableName = 'BlitzFirstResults'

After several successful runs.. run the procedure below to check the health of sql as of a given time

EXEC sp_BlitzFirst @AsOf = '2016-12-01 02:45', @OutputDatabaseName = 'DBAtools', @OutputSchemaName = 'dbo', @OutputTableName = 'BlitzFirstResults'

**What is the expected behavior?**

To see the results of health of SQL Server +-15 minutes of the supplied time

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Windows 2012 R2 w/SQL 2008 R2 SP3, SQL 2012 SP3, SQL 2014 SP2

**Comment by BrentOzar** [comment] 2016-12-02 00:20
Thanks, but search for bugs before you open an issue. Closing this one as a duplicate of #499.

**Closed by BrentOzar** 2016-12-02 00:20 UTC
