### ISSUE TITLE
sp_Blitz - Incorrect "Findings" listing for Alerts and operators?

### ISSUE THREAD

**Issue by PJ777** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1058] opened 2017-08-03 11:20 UTC
Version Aug 01 12:00AM

Despite creating the necessary alerts, upon executing sp_Blitz it lists the following findings:-

Alerts configured without follow up
No Alerts for corruption
No Alerts for Sev 19-25
No Operators Configured/Enabled
Not All alerts configured

The problem is I have an operator created, it is assigned to alerts for 823,824,825, 016-025.
The alerts were created with the script from your website and this has worked fine before.

This is happening on a fresh install of 12.0.5546 on Windows 2008R2 SP1. I would not expect these findings to be listed and this has worked fine in a previous version.

Regards,
PJ777

**Comment by BrentOzar** [comment] 2017-08-03 11:25
Hi, and thanks for the report. It looks like that's a dupe of the things Erik fixed in #1053. Can you grab the current dev version here and see if that fixes it: 

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_Blitz.sql

**Comment by PJ777** [comment] 2017-08-03 11:29
Hi Brent Ozar,

Yes the dev version provided does report the findings concerning Alerts/Operators correctly, none of them appeared this time.

Regards,
PJ777

**Comment by BrentOzar** [comment] 2017-08-03 11:30
OK, great, thanks! Closing.

**Closed by BrentOzar** 2017-08-03 11:30 UTC
Labels: bug, sp_Blitz
