### ISSUE TITLE
sp_BlitzLock - Parallel Deadlocks not showing in first result set

### ISSUE THREAD

**Issue by Adedba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2286] opened 2020-02-12 14:14 UTC
**Version of the script**
SELECT @Version = '2.92', @VersionDate = '20200123';

**What is the current behavior?**
First result set not populated when the only deadlock present is a parallel deadlock

**If the current behavior is a bug, please provide the steps to reproduce.**
Not sure how to reproduce a parallel deadlock, fortunately the system I am working on gets them all the time it seems. 

Run sp_BlitzLock with default parameters

First result set is not populated but the second resultset is populated with findings.

**What is the expected behavior?**

Expect both result sets to be available with the first showing the deadlock graph xml

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

Only tested with SQL 2012 SP4

Please don't shoot me, I am not entirely sure if this is a bug or not  :P

Here is the output sp_BlitzLock @Debug = 1;

Result set 1 empty
Result set 2 has findings
#deadlock_process temp table has deadlock information
#deadlock_resource_parallel temp table has information too

![BlitzLock1](https://user-images.githubusercontent.com/33764798/74342622-afa32700-4da1-11ea-9ff9-d525a177dad2.png)
![BlitzLock2](https://user-images.githubusercontent.com/33764798/74342623-b03bbd80-4da1-11ea-80ee-92395ce9938b.png)

Looking at the code I can see: 

```
CROSS APPLY (SELECT TOP 1 * FROM  #deadlock_resource_parallel AS drp WHERE drp.owner_id = dp.id AND drp.wait_type = 'e_waitPipeNewRow' ORDER BY drp.event_date) AS cao
CROSS APPLY (SELECT TOP 1 * FROM  #deadlock_resource_parallel AS drp WHERE drp.owner_id = dp.id AND drp.wait_type = 'e_waitPipeGetRow' ORDER BY drp.event_date) AS caw
```

If I change the CROSS APPLY to OUTER APPLY for both it returns a result with owner_mode 'e_waitPipeNewRow'

From what I can see I think it might be where only one of the wait types ('e_waitPipeNewRow' or 'e_waitPipeGetRow') exist but not both.

**Comment by Adedba** [comment] 2020-02-12 21:47
Forgot to add the deadlock xml, will grab that tomorrow!

**Comment by Adedba** [comment] 2020-02-13 12:18
Cannot grab the whole thing as there is too much vendor data in there but here is the resource list: 

`<resource-list>
    <exchangeEvent id="Pipe741ae4790" WaitType="e_waitPipeNewRow" nodeId="8">
      <owner-list>
        <owner id="process755034cf8" />
      </owner-list>
      <waiter-list>
        <waiter id="process74649dc38" />
      </waiter-list>
    </exchangeEvent>
    <exchangeEvent id="Pipef4dccd870" WaitType="e_waitPipeNewRow" nodeId="6">
      <owner-list>
        <owner id="process4208c1498" />
      </owner-list>
      <waiter-list>
        <waiter id="process755034cf8" />
      </waiter-list>
    </exchangeEvent>
    <exchangeEvent id="Pipe741ae5ea0" WaitType="e_waitPipeGetRow" nodeId="8">
      <owner-list>
        <owner id="process74649dc38" />
      </owner-list>
      <waiter-list>
        <waiter id="process755025c38" />
      </waiter-list>
    </exchangeEvent>
    <exchangeEvent id="Pipef4dcccd90" WaitType="e_waitPipeGetRow" nodeId="6">
      <owner-list>
        <owner id="process755025c38" />
      </owner-list>
      <waiter-list>
        <waiter id="process4208c1498" />
      </waiter-list>
    </exchangeEvent>
  </resource-list>`

So both wait types are present so its not that, but wondering if instead it may be where a process can be either an owner or waiter for either of the wait types - in which case the following may resolve:

`CROSS APPLY (SELECT TOP 1 * FROM  #deadlock_resource_parallel AS drp WHERE (drp.owner_id = dp.id OR drp.waiter_id = dp.id) AND drp.wait_type = 'e_waitPipeNewRow' ORDER BY drp.event_date) AS cao
CROSS APPLY (SELECT TOP 1 * FROM  #deadlock_resource_parallel AS drp WHERE (drp.owner_id = dp.id OR drp.waiter_id = dp.id) AND drp.wait_type = 'e_waitPipeGetRow' ORDER BY drp.event_date) AS caw`

Tested and gets me a result but I am a little out of depth here because digging into parallel deadlock xml is new to me! haha , hopefully this helps identify if this is an issue or not though :)

**Comment by erikdarlingdata** [comment] 2020-02-16 14:00
If you use outer apply for both of those, do you get duplicate results back?

**Comment by Adedba** [comment] 2020-02-16 17:02
Hey Erik! Nope just the one row returned, can probably get a screenshot of that tomorrow if that helps?

**Comment by erikdarlingdata** [comment] 2020-02-16 17:05
No need for a screenshot, just wanted to verify. This change should be fine otherwise if you just want to push it through. Brent just merged some other changes for this proc in, so make sure you're working with an updated branch.

**Comment by Adedba** [comment] 2020-02-16 17:13
Kool thanks! I will grab the latest version tomorrow and run it to test then make the outer apply change and test again to make sure I get the same issue replicated then I will submit a pull request.

**Comment by Adedba** [comment] 2020-02-17 17:12
Grabbed the latest revision and replicated the issue as expected, I tried the following two changes:

- Changed Cross apply to Outer apply - this returned one row as expected but waiter_mode was NULL

- Left the cross apply but added the two OR clauses I mentioned previously - this also returned one row as expected but gave me a waiter_mode instead of a NULL

See below for the results, not entirely sure which of the two is the expected result - I am leaning towards the one with owner_mode and waiter_mode, let me know what you think.

![image](https://user-images.githubusercontent.com/33764798/74674136-9e468a00-51a8-11ea-9928-c4c641a5fb8c.png)

![image](https://user-images.githubusercontent.com/33764798/74674134-9d155d00-51a8-11ea-89d5-514d83586ada.png)

**Comment by erikdarlingdata** [comment] 2020-02-17 17:14
Yeah, the one with an OR won't work because each APPLY feeds into a different set of columns. You need both.

**Comment by Adedba** [comment] 2020-02-17 17:17
Outer apply for the win?

**Comment by erikdarlingdata** [comment] 2020-02-17 17:17
Yep!

**Comment by BrentOzar** [comment] 2020-02-21 15:36
Looks good, thanks! It'll be in the March release and I'll credit you in the release notes.

**Closed by BrentOzar** 2020-02-21 15:36 UTC

**Comment by abnersimmadhri** [comment] 2021-03-09 18:26
Not sure if this is a bug but this behavior seems inconsistent. 

**Problem**
Parallel deadlocks not showing when results are saved to database table. 
If execute sp_BlitzLock with no parameters it shows both regular and parallel deadlocks, however if I pass a database parameter then the table "BlitzLock" only contains regular deadlocks.  

**Version**
SELECT @Version = '8.01', @VersionDate = '20210222';

**Run the following to reproduce:**
EXEC sp_BlitzLock
Parallel deadlocks included here
![image](https://user-images.githubusercontent.com/8105977/110518264-92f83080-8114-11eb-8f20-6e677b1f3c7a.png)

EXEC sp_BlitzLock
@OutputDatabaseName = 'HealthCheck',

Results in table excludes Parallel deadlocks
![image](https://user-images.githubusercontent.com/8105977/110518481-cfc42780-8114-11eb-8d08-a8d8af3da5d7.png)

**Comment by erikdarlingdata** [comment] 2021-03-09 18:27
@abnersimmadhri this seems to be a new issue -- feel free to open one. i'll take a look at it.
