### ISSUE TITLE
sp_BlitzIndex fails on partially contained databases

### ISSUE THREAD

**Issue by SQLMonger** [BrentOzarULTD/SQL-Server-First-Responder-Kit#607] opened 2016-11-22 17:36 UTC
After updating to SQL 2016 SP1, I also updated to the latest version of the sp_Blitz procs (v4.5 20161115). Unfortunately, sp_BlitzIndex now blows up in the 'Gathering Computed Column Info.' section around line 1586. 

Here is the error text:

Gathering Computed Column Info. Failure populating temp tables. Msg 2787, Level 16, State 1, Procedure sp_BlitzIndex, Line 1620 [Batch Start Line 4]

Invalid format specification: '%.%' THEN 1 ELSE 0 END AS is_function, 'ALTER TABLE ' + QUOTENAME(s.name) + '.' + QUOTENAME(t.name) + ' ADD ' + QUOTENAME(c.name) + ' AS ' + cc.definition + CASE WHEN is_persisted = 1 THEN ' PERSISTED' ELSE '' END + ';' AS [column_definition] FROM [Production-db].sys.computed_columns AS cc JOIN [Production-db].sys.columns AS c ON cc.object_id = c.object_id AND cc.column_id = c.column_id JOIN [Production-db].sys.tables AS t ON t.object_id = cc.object_id JOIN [Production-db].sys.schemas AS s ON s.schema_id = t.schema_id OPTION (RECOMPILE);'.

Msg 50000, Level 16, State 1, Procedure sp_BlitzIndex, Line 1624 [Batch Start Line 4]

Production-db database failed to process. Cannot resolve collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Latin1_General_100_CI_AS_KS_WS_SC" in add operator occurring in SELECT statement column 11.

The solution was to add a COLLATE statement to line 1599 (line 1605 in the delivered script file):

CASE WHEN is_persisted = 1 THEN '' PERSISTED'' ELSE '''' END + '';''  collate SQL_Latin1_General_CP1_CI_AS AS [column_definition]

Cheers,

Clayton

Posted here first: [http://dba.stackexchange.com/questions/156049/sp-blitzindex-v-4-5-2016-11-15-failing-with-collation-error](http://dba.stackexchange.com/questions/156049/sp-blitzindex-v-4-5-2016-11-15-failing-with-collation-error)

**Comment by BrentOzar** [comment] 2016-11-22 17:38
Please include the collation error.

**Comment by SQLMonger** [comment] 2016-11-22 17:41
Sorry Brent. Hit the button before I was done writing...

**Comment by BrentOzar** [comment] 2016-11-22 17:59
I just verified that it doesn't fail with a collation error on my installs. There may be something specific about your install, but we'd need more info to troubleshoot that.

**Comment by BlitzErik** [comment] 2016-11-22 18:04
Same here goes in fine on mine.

**Comment by SQLMonger** [comment] 2016-11-22 18:23
What info would help? I'm pretty certain that we don't us any odd collations. Database has been migrated/upgraded from SQL 2008 to SQL 2016 SP1. Prior versions of sp_BlitzIndex worked fine, and I believe they worked prior to applying SP1.  I just tried version 4.2 20160903, and it worked without error.

**Comment by BlitzErik** [comment] 2016-11-22 18:26
The error message would be a good start.

**Comment by BrentOzar** [comment] 2016-11-22 18:27
@BlitzErik - hold off til you get to a desktop. He's updated the original post with the full error message. I'm digging into it now - it has to do with the persisted computed column definition.

**Comment by SQLMonger** [comment] 2016-11-22 18:28
We do have several tables with persisted computed columns. Let me know if you need anything else.

**Comment by BrentOzar** [comment] 2016-11-22 18:33
OK, I just spent a few minutes trying to reproduce it, and I've been unable to. Here's what I did:

https://gist.github.com/BrentOzar/66f52a7b59a3dabf772a376cbf039850

sp_Blitz worked every time there. So can I ask for a little more details about:

- How you're calling sp_BlitzIndex (options, what database you're in, etc, do any of the options work)
- The collations of your master, tempdb, and user database (does this work for some databases but not others, for example)

**Comment by BlitzErik** [comment] 2016-11-22 18:33
Ah! My bad. Airplane emails. You can assign it to me if you're busy with
stuff. I'll be online in about 30.

**Comment by SQLMonger** [comment] 2016-11-22 19:02
No options specified, calling it from the database I want analyzed. Works in master, model, msdb, scratchpad (small database with a few heap tables). Fails in production and reporting databases. Reporting DB has no persisted computed columns, but does have some XML columns. Tried on a dev database server as well with slightly different results. The Reporting database worked, but the application db failed.
I tried specifying tables, one with a persisted computed column and one without. Both calls fail at the same point.  All servers are at SQL 2016 SP1. Production environment is an AlwaysOn Availability Group.

(I can't open the link you posted above) 

**Collations**: 
master - SQL_Latin1_General_CP1_CI_AS
tempdb - SQL_Latin1_General_CP1_CI_AS
Production - SQL_Latin1_General_CP1_CI_AS
Reporting - SQL_Latin1_General_CP1_CI_AS


Here is a mockup similar to one the tables with a computed column:
`CREATE TABLE [Core].[WFItem](
	[WorkflowItemId] [uniqueidentifier] NOT NULL,
	[WorkflowId] [uniqueidentifier] NOT NULL,
	[PaymentCost] [money] NULL,
	[BonusCost] [money] NULL,
	[TransactionCost] [money] NULL,
	[PlatformCost] [money] NULL,
	[LedgerId] [uniqueidentifier] NULL,
	[Cost]  AS ((isnull([PaymentCost],(0))+isnull([BonusCost],(0)))+isnull([PlatformCost],(0))) PERSISTED NOT NULL,
 CONSTRAINT [PK_WFItem] PRIMARY KEY CLUSTERED 
(
	[WorkflowItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
`

**Comment by BrentOzar** [comment] 2016-11-22 19:14
Hmm, something doesn't seem right there - all of your database collations in that list are the SAME, so there shouldn't be any collation errors.

The mockup create table command doesn't work - it fails with this error, and that the Core schema doesn't exist:

Msg 1709, Level 16, State 1, Line 1
Cannot use TEXTIMAGE_ON when a table has no text, ntext, image, varchar(max), nvarchar(max), non-FILESTREAM varbinary(max), xml or large CLR type columns.

I tweaked those, created the table, and I still don't get the error.

I think we're missing something in the repro. Let's do this: when you get home (or to a less-restrictive network), open that gist link from me to see an example of what a repro script looks like. Then create a new database from scratch, create whatever objects you want to create in there, and get to the point where you can reproduce sp_BlitzIndex failing.

Sorry to make you go through a few extra hoops - I really wish I could see what's going on here to save you that trouble. Thanks!

**Comment by SQLMonger** [comment] 2016-11-22 20:37
Got the gist file... Link won't open in Edge, but it does in Chrome.
My bad on the script. I pared it down too aggressively & cut the XML columns out.
No issues running your test script as provided. I've taken the full table script for the one I thought might be the problem, and created it in the test database. No issues after that either.
Created an empty database with ` CONTAINMENT = PARTIAL` and I get the error when running sp_BlitzIndex... Changed the containment on the DB your script created and re-tested. Boom. Same error.
There you have it.
Very odd that having containment enabled would cause an issue with collations.

**Comment by BrentOzar** [comment] 2016-11-22 20:45
OK, in the interest of creating the simplest test script possible:

CREATE DATABASE [ContainYourself]
 CONTAINMENT = PARTIAL
 ON  PRIMARY 
( NAME = N'ContainYourself', FILENAME = N'M:\MSSQL\Data\ContainYourself.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ContainYourself_log', FILENAME = N'M:\MSSQL\Data\ContainYourself_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO

sp_BlitzIndex @DatabaseName = 'ContainYourself'

Fails with this error:

Msg 2787, Level 16, State 1, Procedure sp_BlitzIndex, Line 1620 [Batch Start Line 8]
Invalid format specification: '%.%' THEN 1 ELSE 0 END AS is_function,
   					   		   'ALTER TABLE ' + QUOTENAME(s.name) + '.' + QUOTENAME(t.name) + 
   					   		   ' ADD ' + QUOTENAME(c.name) + ' AS ' + cc.definition  + 
							   CASE WHEN is_persisted = 1 THEN ' PERSISTED' ELSE '' END + ';' AS [column_definition]
   					   FROM    [ContainYourself].sys.computed_columns AS cc
   					   JOIN    [ContainYourself].sys.columns AS c
   					   ON      cc.object_id = c.object_id
   					   		   AND cc.column_id = c.column_id
   					   JOIN    [ContainYourself].sys.tables AS t
   					   ON      t.object_id = cc.object_id
   					   JOIN    [ContainYourself].sys.schemas AS s
   					   ON      s.schema_id = t.schema_id
					   OPTION (RECOMPILE);'.
Msg 50000, Level 16, State 1, Procedure sp_BlitzIndex, Line 1624 [Batch Start Line 8]
ContainYourself database failed to process. Cannot resolve collation conflict between "SQL_Latin1_General_CP1_CS_AS" and "Latin1_General_100_CI_AS_KS_WS_SC" in add operator occurring in SELECT statement column 11.

**Comment by swasheck** [comment] 2016-11-22 20:59
More information here: https://msdn.microsoft.com/en-us/library/ff929080.aspx

You'll get the same behavior when you try to run `sp_estimate_data_compression_savings` against indexes in a contained database. Any process that uses tempdb with contained database objects needs to specify collation.

**Comment by BrentOzar** [comment] 2016-11-22 21:15
This is such a hot mess. In that link from @swasheck, Books Online says:

> The catalog collation is used for system metadata and transient objects. Details are provided below. In a contained database, the catalog collation Latin1_General_100_CI_AS_WS_KS_SC. This collation is the same for all contained databases on all instances of SQL Server and cannot be changed.

Except that's not true. It turns out only some fields flip:

- Non-contained database: columns.name is SQL_Latin1_General_CP1_CS_AS
- Contained database: columns.name is Latin1_General_100_CI_AS_KS_WS_SC (as BOL describes)
- But in both contained and non-contained databases, computed_columns.definition is SQL_Latin1_General_CP1_CS_AS

So the really dumb part is that only the columns.name collation changes between contained and non-contained databases. If anyone at home wants to play along with Guess The DMV Field's Collation, you can use this:

SELECT SCHEMA_NAME(o.schema_id) AS schema_name, o.name, c.name, c.collation_name
FROM sys.all_columns c
INNER JOIN sys.all_objects o ON c.object_id = o.object_id
WHERE o.name IN ('columns', 'computed_columns')
  AND SCHEMA_NAME(o.schema_id) = 'sys'
  AND c.collation_name IS NOT NULL
ORDER BY 1, o.name, c.name

**Comment by swasheck** [comment] 2016-11-22 21:24
@BrentOzar  that's a good point about the msdn link. Having said that, "partially contained" databases seem like a "partially-implemented" feature.

**Comment by SQLMonger** [comment] 2016-11-22 21:26
@BrentOzar I get three different collation across the 13 tables returned...
SQL_Latin1_General_CP1_CI_AS
Latin1_General_100_CI_AS_KS_WS_SC
Latin1_General_CI_AS_KS_WS

**Comment by BrentOzar** [comment] 2016-11-22 21:27
Yeah, this is likely to be a hot mess to implement. I'm amazed that any of sp_BlitzIndex works here given the partial-implementation of partially-contained DMVs. I'll leave the issue open in case anybody wants to tackle it though.

**Comment by SQLMonger** [comment] 2016-11-22 21:31
I already fixed it. Not sure it will work in all cases, but it worked for me:
Change code on line 1607 from:

`CASE WHEN is_persisted = 1 THEN '' PERSISTED'' ELSE '''' END + '';'' AS [column_definition]`

To:
`CASE WHEN is_persisted = 1 THEN '' PERSISTED'' ELSE '''' END + '';'' COLLATE SQL_Latin1_General_CP1_CI_AS AS [column_definition]`

**Comment by BlitzErik** [comment] 2016-11-22 21:40
Would someone mind checking to see if COLLATE DATABASE_DEFAULT fixes it? This might be a more flexible option if it does.

**Comment by SQLMonger** [comment] 2016-11-22 21:44
That Works.

**Comment by swasheck** [comment] 2016-11-22 21:45
@BlitzErik I've been writing my own compression analysis script and `COLLATE DATABASE_DEFAULT` was the most straightforward way around this that I found.

**Comment by BlitzErik** [comment] 2016-11-22 21:47
@swasheck yeah, i had a feeling it might be. slightly OT, but have you ever run into a spot where it failed? just thinking ahead if anything else pops up with this.

**Comment by BrentOzar** [comment] 2016-11-28 16:54
Good work sir! Thanks, closed as fixed. This will be in the December release.

**Closed by BrentOzar** 2016-11-28 16:54 UTC
Labels: bug, sp_BlitzIndex

**Comment by zulander1** [comment] 2019-06-01 19:39
I am having the same issue, not sure if it is fixed or  not, db collation is SQL_Latin1_General_CP1_CI_AI

Msg 451, Level 16, State 1, Procedure dbo.sp_BlitzIndex, Line 2448 [Batch Start Line 0]
Cannot resolve collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "SQL_Latin1_General_CP1_CI_AI" in add operator occurring in ORDER BY statement column 3.
