### ISSUE TITLE
Error Msg 357 running sp_BlitzCache

### ISSUE THREAD

**Issue by AvP-DBA** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1754] opened 2018-09-10 12:55 UTC
**Do you want to request a *feature* or report a *bug*?**
 - I want to report a **bug** in version 6.9 (20180901)

**What is the current behavior?**
- RedGate SQLMonitor inserted something in a nvarchar(max) column.
- The compiled parameter in the query plan for this insertion looks like this:
> N'?‹????????í?sªHò«PÜÕ­ÖË) ?³/I•QÌãâ¯?òv¯^¥,¢“È.‚?ø^rŸþf˜??Q!(à+ó‡afº§»é™éî¡¯¥¹ñc¤)ú?ý?õ¶Ðtë†žÛöò×jÕšÎÁB±*?uj?–ñbW¦Æ¢jý­YÀü?Ì*Ç0õ*sYµ`?KØ?M}?¦¥?ú
ÍVXšº[©Ú?^3?ž©Ô™Z­ÂÐ·×wŠ=Kàï?Ð§€ÜÞ^K¶bƒ?Ðm?]/lI],5@yÅ2x³oèöXhÉ?%Åû{aL}›=?O•o¶ù:?ƒé\_é¯@\ÎzÆëÓ¿þñÖù?ZŸ)Š??('

- sp_BlitzCache throws an Error 357 (Invalid length parameter passed to the LEFT or SUBSTRING function.) during execution, when executed with @OnlyQueryHashes = query_hash_of_that_statement

> Inserting variables for other procs
Updating procs
**Meldung 537, Ebene 16, Status 3, Prozedur sp_BlitzCache, Zeile 3373
Ein ungültiger Längenparameter wurde an die LEFT- oder SUBSTRING-Funktion übergeben.
Die Anweisung wurde beendet.**
Updating SET options
Updating conversion XML

- The output of sp_BlitzCache does seem "normal" though, except for that message, which causes our Agent Job for BlitzFirst Logging to appear as failed.

**What is the expected behavior?**

- No error message somehow? As the procedure seems to complete successfully, apart from that.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**

- This currently affects SQL Server 2014 SP1 CU1 (12.0.4416) on Windows Server 2012 R2 Standard.
- We have encountered this problem in previous versions of sp_BlitzCache (July 2018 and some other version before that, too.)

**Comment by BrentOzar** [comment] 2018-09-10 13:04
OK, great. Since you're able to reproduce the error (obviously I don't have an insert script that looks like that, hahaha) feel free to dig in and troubleshoot the script.

I would suggest, though, that I wouldn't bother tuning Redgate SQL Monitor's queries. If you have a question about one of their queries, go ahead and open a support call with them.

If you'd like to contribute a fix for this, you can reopen the issue with your changes.

**Closed by BrentOzar** 2018-09-10 13:04 UTC
