### ISSUE TITLE
sp_DatabaseRestore:  Option to create a clean restore script without executing 

### ISSUE THREAD

**Issue by jackmang** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1435] opened 2018-02-17 02:03 UTC
This would be a new feature.

The current behavior is that @Debug = 1 currently generates a lot of extra output - AND - executes the restore.  There is no option to just generate the script without executing it.

I would propose adding a parameter @script = 1 that would print the restore commands, but inhibit the execution of all script related to performing the actual restore task.  Additionally, when @script = 1, we would want to inhibit any extraneous output unless @debug is also specified for any reason.

In this mode, I would propose that all the calls to sp_CommandExecute be skipped along with their associated command  logging.

Side effects:
One issue that would need to be addressed in order to generate a clean script is that there are some **non-fatal** RAISEERROR() statements that would probably need to be ignored when @script=1 and @debug is not. 

I prematurely created a pull request  #1426 with this functionality.

**Comment by ShawnCrocker** [comment] 2018-02-19 12:11
This is similar to #1185 and #1191

**Comment by BrentOzar** [comment] 2018-02-22 05:43
@jackmang thanks for doing the issue! I know it's a little painful to hear this now that the PR has already been created, but going through this issue process first will help a lot (and you'll see why now, heh.)

Generally speaking, you want to avoid parameters that end up producing code like this, taken from a quick code review:

`IF (@Debug IN (0, 1) AND @Script = 0)`

The debug and script parameters should be independent. You should be able to turn debug on/off independently from turning scripting on/off.

I do like the idea of the new @Script parameter though, that's cool. Just code that in a separate, independent way that doesn't require changes to other parameter behavior. If you need to work on the other existing issues for @Debug mode first in order to clear the way for the later @Script work, that might make sense.

**Comment by BlitzErik** [comment] 2018-02-28 18:19
I'm going to close this as a near-dupe of #1185 and #1191 as @ShawnCrocker noted.

Please refer to those issues when working on this functionality.

Thanks!

**Closed by BlitzErik** 2018-02-28 18:19 UTC
Labels: enhancement, sp_DatabaseRestore
