### ISSUE TITLE
sp_Blitz error Selecting @MSSinceWaitsCleared

### ISSUE THREAD

**Issue by pagesplit** [BrentOzarULTD/SQL-Server-First-Responder-Kit#541] opened 2016-10-18 14:13 UTC
BUG

SELECT @MsSinceWaitsCleared = DATEDIFF(MINUTE, create_date, CURRENT_TIMESTAMP)  * 60000
            FROM    sys.databases
            WHERE   name='tempdb';
encounters an error converting value to int

Selecting create_date in my instance yields
2016-09-20 08:56:51.200

Finding the DATEDIFF would yield
40391

Multiplying by 60000 yields an out of bounds for the INT that DATEDIFF returns
2,423,460,000 > 2,147,483,647

To Fix This the number DATEDIFF multiply must be of BIGINT or the DECIMAL(10,0) or greater

I chose BIGINT 
SELECT 
  @MsSinceWaitsCleared = CAST(DATEDIFF(MINUTE, create_date, CURRENT_TIMESTAMP) AS BIGINT) * 60000
FROM    sys.databases
WHERE   name='tempdb';

This should affect all versions of SQL Server regardless of Operating System

Thanks
Michael

**Comment by BrentOzar** [comment] 2016-10-18 14:14
Duplicate of #526, already fixed in the dev branch. Closing. Thanks!

**Closed by BrentOzar** 2016-10-18 14:14 UTC
