### ISSUE TITLE
sp_BlitzRS Inline TSQL - False Positive

### ISSUE THREAD

**Issue by mshahidusman** [BrentOzarULTD/SQL-Server-First-Responder-Kit#426] opened 2016-08-24 07:27 UTC
I would like to report a tiny bug related to inline TSQL found in dataset. As its scanning command text and looking if keyword “Select” is there or not. If a stored procedure used in report contains ‘Select’ in name it will be in result set as false positive.

**Comment by BrentOzar** [comment] 2016-08-24 13:07
Can you be more specific about the script you're talking about, what the output is, how to reproduce it, etc? I'm not even sure which stored procedure in the First Responder Kit you're talking about. Thanks!

**Comment by BlitzErik** [comment] 2016-08-25 20:33
This is about BlitzRS. He left a comment on the blog about it, and I directed him here. I'll take a look, but since I don't have SSRS set up anywhere, or populated with reports, it would be nice if @mshahidusman made a code suggestion to fix it.

**Comment by mshahidusman** [comment] 2016-08-26 08:15
**Regeneration of Bug:**
Use a stored procedure in report name containing string “Select”, and it will be included as false positive for inline TSQL usage in report.

**Possible Solution:**
Currently In report’s XML we are looking for string “SELECT” at following path “Report/DataSets/DataSet/Query/CommandText”. 

To fix the issue we need to check if node “Report/DataSets/DataSet/Query/CommandText/CommandType” exists and node value is “StoredProcedure” then do not sacn “Report/DataSets/DataSet/Query/CommandText”. We also can go other way around.

Thanks

**Comment by BlitzErik** [comment] 2016-08-26 14:29
Do you have either example XML documents, or XQuery written to parse this? It's helpful information, but since I don't have SSRS to test against, I wouldn't trust any XQuery I'd write to find these values.

**Comment by mshahidusman** [comment] 2016-08-29 07:32
I will update thread soon.

**Comment by mshahidusman** [comment] 2016-08-29 09:02
Hi Erik, 

I have performed extract of Reports from my SSRS, kindly find them in attachment. I hope it will help. Let me know in case you require any additional information.

Thanks 


[Correct Finding.xml.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/442078/Correct.Finding.xml.txt)
[False-Positive.xml.txt](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/files/442077/False-Positive.xml.txt)

**Comment by BlitzErik** [comment] 2016-08-31 12:51
I think I see what's going on. I'll work on this when I have a chance.

**Comment by BlitzErik** [comment] 2017-01-16 16:28
Closing. We're not doing any more development work on sp_BlitzRS.

**Closed by BlitzErik** 2017-01-16 16:28 UTC
Labels: bug, sp_BlitzRS
