### ISSUE TITLE
latest version of sp_Blitz is reporting no Alerts configured, no operators configured etc

### ISSUE THREAD

**Issue by stuben32** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1081] opened 2017-08-25 08:43 UTC
Hi,

Have set up the latest first  responder (AUG) on a new SQL 2016 SP1 - CU4 server.

When running sp_Blitz I get warnings for No Alerts for corruption, no alerts for 19-25, no operators configured, alerts with no follow ups.

They are configured.

If i replace sp_blitz with July's version it correctly identifies that these are set up.

Stuben32

**Comment by BlitzErik** [comment] 2017-08-25 10:31
This is a duplicate of #1054. Please search issues before opening. There's a fix in the dev branch. 

Thanks!

**Closed by BlitzErik** 2017-08-25 10:31 UTC
