### ISSUE TITLE
Create a basic CI setup

### ISSUE THREAD

**Issue by nschonni** [BrentOzarULTD/SQL-Server-First-Responder-Kit#310] opened 2016-06-22 02:05 UTC
Might want to look at Appveyor now that you're open source. You can run some basic smoke tests using a "bad" SSDT project http://www.appveyor.com/docs/deployment/sql-database-ssdt#publishing-to-local-sql-server-for-integration-testing

Having a CI setup would also help enforce stuff like #287 for PRs (and give you a warm fuzzy feeling)

**Comment by BrentOzar** [comment] 2016-06-22 10:49
Yeah, I don't use SSDT, so I'd leave that open to someone else. I'll mark this as Help Wanted.

**Comment by chipitsine** [comment] 2016-08-10 08:15
what is a "bad" SSDT project ?

**Comment by chipitsine** [comment] 2016-08-10 17:54
what if we download AdventureWorks and run procedures on it?
does it look like CI ?

**Comment by BrentOzar** [comment] 2016-08-10 18:03
The problem is that you can't just test on one version of SQL Server - you need to test on SQL 2008, R2, 2012, 2014, and 2016, on case-sensitive instances.

**Comment by chipitsine** [comment] 2016-08-10 18:33
I beleive we can setup test matrix (like running tests on several versions of ms sql):

https://www.appveyor.com/docs/build-configuration#build-matrix

the questions is: how to test ?

**Comment by SelmanAY** [comment] 2016-08-17 06:07
I have tested appveyor for database services sometime ago (one or two months) documentation says there is Sql Server 2016 but i cant get it running. (logs have no error messages or info, it looks like its just skipping relevant configuration from yaml file). 

It also says there are instances with reporting services installed but i cant get them running either. 

i did some test using multiple instances running on same build server without having a build matrix defined. it can be done with build matrix defined it will be more structured. (as far as i understand with a short reading, i need some reading on build matrices)

for testing http://tsqlt.org/ has good features but for this case it is hard to mimic test cases. 

off-topic note: all sql server instances of appveyor is case insensitive.

**Comment by chipitsine** [comment] 2016-08-17 07:07
well, I'm on the way now.
I haven't yet tried sql databases with AppVeyor.
currently, I see few options in AppVeyor itself (but it refuses to start 2012 sql instance) and I can install sql with chocolatey (but it takes toooooo looong).

no luck yet.

**Comment by BrentOzar** [comment] 2016-12-09 23:04
Since there's been no progress on this, and I don't see us setting it up ourselves, I'm going to go ahead and close this.

**Closed by BrentOzar** 2016-12-09 23:04 UTC
Labels: help wanted
