### ISSUE TITLE
sp_BlitzLock Throwing an Error when attempting to output to table

### ISSUE THREAD

**Issue by BilliousBT** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3566] opened 2024-09-10 07:56 UTC
**Version of the script**
8.20

**What is the current behavior?**
Throws error when attempting to output to table

**If the current behavior is a bug, please provide the steps to reproduce.**
`exec sp_BlitzLock @OutputDatabaseName = 'DBAtools', @OutputSchemaName = 'dbo', @OutputTableName = 'BlitzLock'`

returns:
```
Creating synonym DeadlockFindings
Msg 2714, Level 16, State 8, Line 1
There is already an object named 'DeadlockFindings' in the database.
Creating synonym DeadLockTbl
Msg 2714, Level 16, State 8, Line 1
There is already an object named 'DeadLockTbl' in the database.

<bunch of successful messages>

Msg 208, Level 16, State 1, Procedure sp_BlitzLock, Line 3658 [Batch Start Line 0]
Invalid object name 'DeadLockTbl'.
```
Some tables do get created in the target database but are empty.

**What is the expected behavior?**
No error, BlitzLock results are outputted to tables.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Server Enterprise 2022 : 16.04135.4
Windows Server 2016 Standard

**Comment by erikdarlingdata** [comment] 2024-09-11 13:29
@BilliousBT were you planning on working on this issue? Just asking so I can assign it.

**Comment by VladDBA** [comment] 2024-09-11 16:36
@BilliousBT I've been trying to reproduce this issue, but I can't see how it can possibly happen. 
The code checks for the synonyms, drops them if found, and then re-creates them.
Any chance there's someone else or an agent job running sp_BlitzLock at the same time you're running it?

**Comment by BilliousBT** [comment] 2024-09-11 19:20
Just following the boss' orders:  @erikdarlingdata  as much as I'd love to give it a go, I'd struggle to get to it anytime soon.

![image](https://github.com/user-attachments/assets/c10515f2-ff4d-469d-b83e-643a6dc2c87c)

**Comment by BrentOzar** [comment] 2024-09-22 12:21
@VladDBA I actually reproduced it right away on the SQL Server 2022 image that I usually use for teaching, so I asked @BilliousBT to open the issue. I'll work on it when I'm back from vacation.

**Comment by BrentOzar** [comment] 2024-10-08 10:03
The problem is reproducible for me when:

* sp_BlitzLock is in the master database
* My output tables are in database A
* I'm calling sp_BlitzLock inside database A (not a different database)

It is NOT reproducible when I call sp_BlitzLock from any other database.

**Closed** 2024-10-14 14:36 UTC
Labels: bug, sp_BlitzLock
