### ISSUE TITLE
spBlitzFirst job fails once a day, every day

### ISSUE THREAD

**Issue by AdrianB1** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2983] opened 2021-08-30 11:30 UTC
**Version of the script**
8.05, July 25, 2021. Problem exists in older versions too.

**What is the current behavior?**
Running a job every 15 minutes, one per day fails every time at the same time.

**If the current behavior is a bug, please provide the steps to reproduce.**
Start a job with a single step that executes this:
sp_blitzfirst @OutputDatabaseName = 'DBATools',
@OutputSchemaName = 'dbo',
@OutputTableName = 'BlitzFirst',
@OutputTableNameFileStats = 'BlitzFirst_FileStats',
@OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
@OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
@OutputTableNameBlitzCache = 'BlitzCache',
@OutputTableNameBlitzWho = 'BlitzWho',
@OutputTableRetentionDays = 7;

It works every time, except once a day, every day, on a single server at 2PM local time in Bangkok. This is the result of the step after ~ 18 seconds:

Message
Executed as user: NT AUTHORITY\SYSTEM. ...e 50000)  Now starting diagnostic analysis [SQLSTATE 01000] (Message 50000)  Checking for Read intent databases to exclude [SQLSTATE 01000] (Message 50000)  Determining SQL Server version. [SQLSTATE 01000] (Message 50000)  Capturing first pass of wait stats, perfmon counters, file stats [SQLSTATE 01000] (Message 50000)  Logging sp_BlitzWho to table [SQLSTATE 01000] (Message 50000)  Checking for Read intent databases to exclude [SQLSTATE 01000] (Message 50000)  String or binary data would be truncated. [SQLSTATE 22001] (Error 8152)  Warning: The join order has been enforced because a local join hint is used. [SQLSTATE 01000] (Error 8625)  The statement has been terminated. [SQLSTATE 01000] (Error 3621)  Beginning investigatory queries [SQLSTATE 01000] (Message 50000)  Warning: The join order has been enforced because a local join hint is used. [SQLSTATE 01000] (Message 8625)  Warning: The join order has been enforced because a local join hint is used. [SQLSTATE 01000] (Message 8625)  Warning: The join order has been enforced because a local join hint is used. [SQLSTATE 01000] (Message 8625)  Finished running investigatory queries [SQLSTATE 01000] (Message 50000)  Waiting to match @Seconds parameter [SQLSTATE 01000] (Message 50000)  Capturing second pass of wait stats, perfmon counters, file stats [SQLSTATE 01000] (Message 50000)  Analyzing changes between first and second passes of DMVs [SQLSTATE 01000] (Message 50000)  Analysis finished, outputting results [SQLSTATE 01000] (Message 50000)  Calling sp_BlitzCache [SQLSTATE 01000] (Message 50000)  Checking @MinutesBack validity. [SQLSTATE 01000] (Message 50000)  Setting @MinutesBack to a negative number [SQLSTATE 01000] (Message 50000)  Creating temp tables for results and warnings. [SQLSTATE 01000] (Message 50000)  Checking database validity [SQLSTATE 01000] (Message 50000)  Checking sort order [SQLSTATE 01000] (Message 50000)  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000] (Message 50000)  Cleaning up old warnings for your SPID [SQLSTATE 01000] (Message 50000)  Cleaning up old plans for your SPID [SQLSTATE 01000] (Message 50000)  Checking all sort orders, please be patient [SQLSTATE 01000] (Message 50000)  Beginning all sort loop [SQLSTATE 01000] (Message 50000)  Beginning for ALL [SQLSTATE 01000] (Message 50000)  Checking @MinutesBack validity. [SQLSTATE 01000] (Message 50000)  Creating temp tables for results and warnings. [SQLSTATE 01000] (Message 50000)  Checking database validity [SQLSTATE 01000] (Message 50000)  Checking sort order [SQLSTATE 01000] (Message 50000)  Skip Analysis set to 1, hiding Summary [SQLSTATE 01000] (Message 50000)  Cleaning up old warnings for your SPID [SQLSTATE 01000] (Message 50000)  Cleaning up old plans for your SPID [SQLSTATE 01000] (Message 50000)  Creating temp tables for internal processing [SQLSTATE 01000] (Message 50000)  Checking for Read intent databases to exclude [SQLSTATE 01000] (Message 50000)  Checking plan cache age [SQLSTATE 01000] (Message 50000)  Checking for single use plans and plans with many queries [SQLSTATE 01000] (Message 50000)  Setting up variables [SQLSTATE 01000] (Message 50000)  Determining SQL Server version. [SQLSTATE 01000] (Message 50000)  Creating dynamic SQL based on SQL Server version. [SQLSTATE 01000] (Message 50000)  Ignoring readable secondaries databases by default [SQLSTATE 01000] (Message 50000)  Ignoring system databases by default [SQLSTATE 01000] (Message 50000)  Setting minutes back filter [SQLSTATE 01000] (Message 50000)  Applying chosen sort order [SQLSTATE 01000] (Message 50000)  Substituting NULLs for spill columns in older versions of SQL [SQLSTATE 01000] (Message 50000)  Adding additional info columns for newer versions of SQL [SQLSTATE 01000] (Message 50000)  Getting memory grant information for newer versions of SQL [SQLSTATE 01000] (Message 50000)  Substituting NULLs for spill columns in older versions of SQL [SQLSTATE...  The step failed.

**What is the expected behavior?**
No error in the execution.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL 2012 SP4, Windows 2012 R2. Cannot reproduce on any other server.

**Comment by BrentOzar** [comment] 2021-09-01 08:00
OK, just to be clear - are you logging this so that you can troubleshoot it? Because this obviously isn't something that other people can troubleshoot from here if we don't know how to reproduce it.

**Comment by AdrianB1** [comment] 2021-09-01 21:29
Yes, that is the plan; also in case anyone else encounter it, it will appear as a known issue.

**Comment by AdrianB1** [comment] 2021-09-05 14:23
I have installed it on a few more servers and I see 4 more servers with the same error at the same time, 2PM local time. I will spend some time investigating it in the next days. 2 have SQL 2012, 2 have SQL 2016, some are on Standard Edition and some on Enterprise Edition, so the SQL version and edition do not seem to matter.

**Comment by BrentOzar** [comment] 2021-09-14 07:52
OK, it's been a week. I totally understand that this is a problem in your specific environment, but I don't want to keep this in the public issues list until you've narrowed down what's causing it, and we can go from there.

I'll close this for now, but if you narrow down the root cause, feel free to reopen it with the specifics. Thanks!

**Closed by BrentOzar** 2021-09-14 07:52 UTC
Labels: bug, sp_BlitzFirst

**Comment by AdrianB1** [comment] 2021-09-17 10:47
Analysis of 13 failures show 2 points of failure with roughly equal distribution:
1. Message 50000) Creating temp tables for results and w... The step failed.
2. Message 50000) Adding SQL to collect trigger stats. [SQLSTAT... The step failed.

**Comment by BrentOzar** [comment] 2021-09-17 12:42
@AdrianB1: I need you to hear me on this: _I am not doing any further work on this issue. If you narrow down the root cause, feel free to reopen it with the specifics. This isn't something I can troubleshoot from here._

Further notes in this issue will not be a productive exercise for you _unless you can point me to the part of the code that is causing you problems._

I literally have zero idea, none whatsoever, why this is happening to you, and I can't spend the time to randomly root around through the code looking for it.

If you want to work on it, you are absolutely welcome to edit the code, looking for the part that's causing you problems, and then submit a pull request with the changes. However, I can't do that because I can't reproduce this problem on my servers.

Thanks for understanding.

**Comment by AdrianB1** [comment] 2021-09-17 16:55
Brent, I am working on it and I have no expectation from anyone else to do it; I am just sharing updates when I have any. If that is a problem, I will not add comments until I find the cause and fix the problem. I did not reopen it, just added some info. Maybe it is bad habit, this is how we operate in my company (track info in tickets).
