### ISSUE TITLE
SP_Blitz Cache Arithmetic Overflow Computing CPU, duration, read, and write metrics

### ISSUE THREAD

**Issue by ianmanton** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2018] opened 2019-04-05 12:46 UTC
**Version of the script**
@Version = '7.3';
@VersionDate = '20190219';

**What is the current behavior?**
Intermittently - (every 3 hours but presumably thus coinciding with a big recurring job (CDR ETL)) the spblitz process fails at the "Computing CPU, duration, read, and write metrics" step with Msg 8115, Level 16, State 2, Procedure sp_BlitzCache, Line 2164 [Batch Start Line 69] Arithmetic overflow error converting expression to data type money.)  My read count is apparently up to 16 or 17 digits but as Money is being used (for a variable that is only ever an integer?) it's breaching the datatype size and falling over so the procedure aborts.

**What is the expected behavior?**
Not falling over :) Be able to process and sum values greater than the money datatype particularly if no decimal point is used?

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SS2017 CU 14, Windows Server 2016.  Seemingly yes - We have only recently upgraded to the latest release, prior to that we had been running the same version for a year or so (the one before the additional columns needed to be added to the tables between releases) - but it also hasn't been running so frequently so may not have coincided with this hefty activity previously - call it luck!

![ValuesAsMoneyAndNvarcharOnFailedRun](https://user-images.githubusercontent.com/49268750/55628626-21393e80-57a9-11e9-9eb2-68e50317434d.JPG)

Update def up to 17dp (at least) last failure had this as the read value... 22,517,998,719,324,937 !

**Comment by BrentOzar** [comment] 2019-04-23 19:06
Thanks for the bug report, and sorry about that.

Researching it, yeah, looks like the August 2018 release changed from BIGINT to MONEY for those totals, here:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/commit/af71aabba80d73f021fd219af6d6ee4447531f84

It's been fixed in the dev branch, and it'll be in this month's release. Thanks!

**Closed** 2019-04-23 19:06 UTC

**Comment by ianmanton** [comment] 2019-04-24 09:05
Thanks Brent 😊

**Comment by ianmanton** [comment] 2019-05-01 08:56
Hi @BrentOzar - just to check - do we need to change the datatype of the blitzcache table columns back to something else - have now installed the updated FRK (thanks!) but I'm now getting LOTS of Arithmetic Overflow errors on execution instead of the one from before!

Output below:

Setting up configuration variables
Now starting diagnostic analysis
Capturing first pass of wait stats, perfmon counters, file stats
Beginning investigatory queries
Finished running investigatory queries
Waiting to match @Seconds parameter
Capturing second pass of wait stats, perfmon counters, file stats
Analyzing changes between first and second passes of DMVs
Analysis finished, outputting results
Determining SQL Server version.
Calling sp_BlitzCache
Checking @MinutesBack validity.
Setting @MinutesBack to a negative number
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Checking all sort orders, please be patient
Beginning all sort loop
Beginning for ALL
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Msg 8115, Level 16, State 2, Line 3
Arithmetic overflow error converting expression to data type money.
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Including only chosen SQL Handles
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Msg 8115, Level 16, State 2, Line 3
Arithmetic overflow error converting expression to data type money.
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Including only chosen SQL Handles
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Msg 8115, Level 16, State 2, Line 3
Arithmetic overflow error converting expression to data type money.
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Including only chosen SQL Handles
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Msg 8115, Level 16, State 2, Line 3
Arithmetic overflow error converting expression to data type money.
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Including only chosen SQL Handles
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Including only chosen SQL Handles
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Checking @MinutesBack validity.
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Skip Analysis set to 1, hiding Summary
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Processing SQL Handles To Ignore
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Including only chosen SQL Handles
Applying chosen sort order
Getting spill information for newer versions of SQL
Adding additional info columns for newer versions of SQL
Getting memory grant information for newer versions of SQL
Getting spill information for newer versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Skipping analysis, going to results
Displaying analysis of plan cache.
Returning ExpertMode = 0
Writing results to table.
Writing results to table.
sp_BlitzCache Finished

**Comment by ianmanton** [comment] 2019-05-01 09:24
Possibly a clash here? 

![image](https://user-images.githubusercontent.com/49268750/57011776-3a43dc80-6bfb-11e9-9954-295f31bb5d5c.png)

**Comment by BrentOzar** [comment] 2019-05-01 10:55
Can you go ahead and start debugging it? It sounds like you’re able to reproduce the issue easily and it sounds like you’ve got a good idea of what you’re looking for - jump in and give ‘er a shot. I’m tied up for the next few days teaching a class, and I don’t want to hold you back from getting a solution that works for you. Thanks!

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by ianmanton** [comment] 2019-05-01 11:16
That’s about as much as I could work out! The gargantuan code of yours is rather beyond my skill level lol!

All I can see is that the table data type definitions don’t necessarily align with the sections that are casting memory usage/spills to money still.

If I get chance I’ll have a go though but may have to roll back as it now doesn’t run for me at all instead of only failing intermittently lol.

Many thanks
Ian

**Comment by BrentOzar** [comment] 2019-05-01 11:18
OK, cool. If you have time to debug & find it, feel free to open a new issue - I'm going to leave this one closed though. Thanks!

**Comment by ianmanton** [comment] 2019-06-10 14:03
(I raised a suggested fix as a proposed merge the other month - not sure if I did it right as still pending review - but it's there in any case!)
