### ISSUE TITLE
sp_Blitz - identify mount points and don't complain about the same-drives thing

### ISSUE THREAD

**Issue by BlitzErik** [BrentOzarULTD/SQL-Server-First-Responder-Kit#498] opened 2016-10-05 14:59 UTC
Migrated form old repo. Originally submitted (without comment) by @BrentOzar

**Comment by BrentOzar** [comment] 2016-10-13 15:26
Ooo, I actually even have code for this - it's in issue #237, closing this one as a duplicate of that.

**Closed by BrentOzar** 2016-10-13 15:26 UTC
Labels: enhancement, sp_Blitz
