### ISSUE TITLE
String Data Getting Truncated Error - sp_BlitzCache

### ISSUE THREAD

**Issue by imajaydwivedi** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1415] opened 2018-02-08 11:56 UTC
I am executing below code in my active busy server, and its finishing with error -

> Msg 8152, Level 16, State 13, Procedure sp_BlitzCache, Line 2980 [Batch Start Line 0]
> String or binary data would be truncated.

## Code being Used
EXEC dbo.sp_BlitzFirst 
  @OutputDatabaseName = 'FirstResponderKit', 
  @OutputSchemaName = 'dbo', 
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache';

## Output with Error Message
Setting up configuration variables
Now starting diagnostic analysis
Capturing first pass of wait stats, perfmon counters, file stats
Beginning investigatory queries
Finished running investigatory queries
Waiting to match @Seconds parameter
Capturing second pass of wait stats, perfmon counters, file stats
Analyzing changes between first and second passes of DMVs
Analysis finished, outputting results
Calling sp_BlitzCache
Checking @MinutesBack validity.
Setting @MinutesBack to a negative number
Creating temp tables for results and warnings.
Checking database validity
Checking sort order
Cleaning up old warnings for your SPID
Cleaning up old plans for your SPID
Creating temp tables for internal processing
Checking plan cache age
Setting up variables
Determining SQL Server version.
Creating dynamic SQL based on SQL Server version.
Ignoring system databases by default
Setting minutes back filter
Applying chosen sort order
Adding additional info columns for newer versions of SQL
Substituting NULLs for memory grant columns in older versions of SQL
Adding SQL to collect trigger stats.
Collecting execution plan information.
Attempting to aggregate stored proc info from separate statements
Warning: Null value is eliminated by an aggregate or other SET operation.
Computing CPU, duration, read, and write metrics
Update CPU percentage for stored procedures
Gather percentage information from grouped results
Begin XML nodes processing
Gathering high level plan information
Warning: Null value is eliminated by an aggregate or other SET operation.
Performing compile timeout checks
Performing compile memory limit exceeded checks
Performing unparameterized query checks
Performing index DML checks
Performing table DML checks
Gathering row estimates
Gathering statement costs
Updating statement costs
Gathering stored procedure costs
Checking for plan warnings
Checking for implicit conversion
Performing busy loops checks
Performing TVF join check
Checking for operator warnings
Checking for table variables
Checking for functions
Checking for expensive key lookups
Checking for expensive remote queries
Checking for expensive sorts
Checking for icky cursors
Checking for bad scans and plan forcing
Checking for computed columns that reference scalar UDFs
Checking for filters that reference scalar UDFs
Checking modification queries that hit lots of indexes
Checking for Spatial index use
Checking for wonky Index Spools
Checking for forced serialization
Checking for ColumnStore queries operating in Row Mode instead of Batch Mode
Checking for downlevel cardinality estimators being used on SQL Server 2014.
Performing query level checks
Gathering additional plan level information
Warning: Null value is eliminated by an aggregate or other SET operation.
Attempting to get stored procedure name for individual statements
Trace flag checks
Is Paul White Electric?
Getting information about implicit conversions and stored proc parameters
Getting variable info
Getting conversion info
Parsing conversion info
Inserting variables
**Msg 8152, Level 16, State 13, Procedure sp_BlitzCache, Line 2980 [Batch Start Line 0]
String or binary data would be truncated.
The statement has been terminated.**
Updating procs
Updating conversion XML
Updating cached parameter XML
Setting configuration values
Checking for query level SQL Server issues.
Checking for forced parameterization and cursors.
Populating Warnings column
Populating Warnings column for stored procedures
Checking for plans with >128 levels of nesting
Checking for plans with no warnings
Writing results to table.
sp_BlitzCache Finished

**Comment by BrentOzar** [comment] 2018-02-08 12:08
Thanks for the parameters and the output messages. That helps get us started on troubleshooting.

Based on your input parameters, you're calling sp_BlitzFirst, which then calls sp_BlitzCache. It looks like the problem is inside sp_BlitzCache in the tables it's writing to disk.

Here's the tough part: from here, I can't tell which field is getting truncated. This is a notorious error from SQL Server - I really wish they'd tell us which field is involved. 

I hate to say this, but for you to get this problem solved, you're going to have to figure out which field is involved. Look at the schema of the dbo.BlitzCache table, and then run sp_BlitzCache by itself (without writing anything to disk.) Look at the output fields to see if something's wider than the field definitions. For example, maybe it's the QueryType column - maybe you have really, really long names for stored procedures or functions. Once you figure that out, let us know and we may be able to get a workaround.

I'll leave this issue open for a couple of days if you want to work on it, but if I don't hear an answer back from you, I'll close it.

**Comment by BlitzErik** [comment] 2018-02-08 12:18
Make sure you're on the newest version of the procs. I've done a lot of work to fix these problems.

**Comment by imajaydwivedi** [comment] 2018-02-08 12:48
Hi Brent/Erik,

Thanks for your help. Its resolved now. Yes I am using latest code from
github.

Following Brent's debugging suggestion, now its running successfully after
changing length of Column  [compile_time_value] from 128 to 250 in
[sp_BlitzCache] proc. The data I am getting is of 203 characters.

CREATE TABLE #stored_proc_info
(
    SPID INT,
SqlHandle VARBINARY(64),
    QueryHash BINARY(8),
    variable_name NVARCHAR(128),
    variable_datatype NVARCHAR(128),
converted_column_name NVARCHAR(128),
    compile_time_value NVARCHAR(255), /* Ajay:- NVARCHAR(128) ->
NVARCHAR(255) */
    proc_name NVARCHAR(300),
    column_name NVARCHAR(128),
    converted_to NVARCHAR(128)
);

Thanks a lot for your time on this silly bug :)


Best Regards,
Ajay Dwivedi

**Comment by BlitzErik** [comment] 2018-02-08 12:50
Ajay -- if you were on the latest version, that table would have this definition.

![image](https://user-images.githubusercontent.com/11590415/35973800-bfd2b96e-0ca4-11e8-87d7-cf865b0b1688.png)

Time to get downloading, buddy ;)

**Closed** 2018-02-08 12:51 UTC

**Comment by imajaydwivedi** [comment] 2018-02-08 12:57
Thanks Eric. Seems my mistake :). You people are awesome.



Best Regards,
Ajay Dwivedi
