### ISSUE TITLE
Sp_allNightLog reports success of backups when fileshare is inaccessible.

### ISSUE THREAD

**Issue by scorellis** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1238] opened 2017-11-17 18:42 UTC
While performing an initial setup of sp_allnightlog on a server, we observed that the backup_worker table shows the backup completed, is_completed = 1 and error_number = NULL.

**Comment by BrentOzar** [comment] 2017-11-17 18:42
OK, have you got any more detailed repro steps? Does this happen every time? If so, can you run it with debug on and copy/paste the messages list into the issue?

**Comment by BrentOzar** [comment] 2017-11-17 18:44
Also, check that it's not related to this existing issue - if the first restore fails (like if the backup file is corrupt, or SQL Server doesn't have permissions to it) then it'll fail:

https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/1000

**Comment by scorellis** [comment] 2017-11-17 20:11
When the service account running SQL doesn't have permissions to access the network share, it fails silently.  There were no useful messages that I recall seeing in debug.  It said it was doing it then walked on by to the next one.

**Comment by BrentOzar** [comment] 2017-11-17 20:18
OK, perfect, yeah, that's a dupe of #1000 then. I'm going to close this one, but do you want to test the code Erik checked in for #1000 over in that ticket? If so, head over there and try that one.

**Closed by BrentOzar** 2017-11-17 20:18 UTC
