### ISSUE TITLE
sp_DatabaseRestore dependency fault

### ISSUE THREAD

**Issue by paulholmes-london** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1064] opened 2017-08-15 00:06 UTC
I'm using https://raw.githubusercontent.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/dev/Install-All-Scripts.sql
for automated instance build.

After curling the file in - MacOS yah ;) - playing in via MS supplied *nix SQLCMD - (more goodness, yah :) )

I'm getting:

"The module 'sp_AllNightLog' depends on the missing object 'master.dbo.sp_DatabaseRestore'. The module will still be created; however, it cannot run successfully until the object exists."

-- 

Does the Install-All-Scripts.sql in the above URL have external dependencies? (i.e. something else to play in sp_DatabaseRestore ?)

**Comment by BrentOzar** [comment] 2017-08-15 00:58
Yeah, you may only want to use the install core scripts instead.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by paulholmes-london** [comment] 2017-08-15 22:36
That worked, so I'm sorted.

Should this issue be left open, or is the dependency in Install-All-Scripts by design?

**Comment by BrentOzar** [comment] 2017-08-15 23:42
No, we'll close this. That dependency is by design.

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Closed** 2017-08-16 00:35 UTC
