### ISSUE TITLE
RegOpenKeyEx() returned error 2, 'The system cannot find the file specified.'

### ISSUE THREAD

**Issue by ScottL1969** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2836] opened 2021-03-23 16:18 UTC
**Version of the script**
	SELECT @Version = '8.01', @VersionDate = '20210222';

**What is the current behavior?**
When I execute the script, I get this error.   It would be nice to have a clean run with no error.
RegOpenKeyEx() returned error 2, 'The system cannot find the file specified.'
Msg 22001, Level 1, State 1

Lines of code:
								DECLARE @outval VARCHAR(36);
								/* Get power plan if set by group policy [Git Hub Issue #1620] */						
								EXEC master.sys.xp_regread @rootkey = 'HKEY_LOCAL_MACHINE',
														   @key = 'SOFTWARE\Policies\Microsoft\Power\PowerSettings',
														   @value_name = 'ActivePowerScheme',
														   @value = @outval OUTPUT;

**If the current behavior is a bug, please provide the steps to reproduce.**
Rune code on SQL Server with no GPO.

**What is the expected behavior?**
No error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL Version (@@Version)  Microsoft SQL Server 2017 (RTM-CU22-GDR) (KB4583457) - 14.0.3370.1 (X64)   Nov  6 2020 18:19:52   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

OS Windows 2012 R2.

**Comment by BrentOzar** [comment] 2021-03-24 05:30
OK, this isn't something I can repeat here, nor have I ever seen across thousands of SQL Servers. I'm not saying it doesn't happen - I'm sure it does - but I'm saying that there's no way I can reproduce this, and it sounds like you can reproduce it pretty quickly. 

Can you troubleshoot the code on your end and then do a pull request with the necessary changes to get it to work? Otherwise I'm afraid I'm going to have to close this one - I don't think it's fair to ask volunteers to troubleshoot something that complex in your environment. Is that fair?

**Comment by ScottL1969** [comment] 2021-03-24 15:00
For me, it errors out on every SQL Server because we do not have GPO power plan.      It does not find the registry entry, thus the errors.     I found this solution in a google search.   
 Adding ,   @no_output = 'no_output' to the call makes @outval return a null.    If its null, then you can do the other checks?



								DECLARE @outval VARCHAR(36);
								/* Get power plan if set by group policy [Git Hub Issue #1620] */						
								EXEC master.sys.xp_regread @rootkey = 'HKEY_LOCAL_MACHINE',
														   @key = 'SOFTWARE\Policies\Microsoft\Power\PowerSettings',
														   @value_name = 'ActivePowerScheme',
														   @value = @outval OUTPUT,
														   @no_output = 'no_output';

This is sample code to print 'RegVal not found.' if @outval is null.
														   SELECT isnull(@outval,'RegVal not found.')

**Comment by BrentOzar** [comment] 2021-03-29 05:54
OK, can you do a pull request as described in the contributing guide:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/CONTRIBUTING.md

If you can't do that, just let me know and another volunteer may be able to help. Just trying to be respectful of everyone's time here. Thanks for understanding!

**Comment by ScottL1969** [comment] 2021-03-31 21:58
It would be best for someone else to test this out.   I do not get output for the checks right after.    If they put in the code and check for null, they can do the next checks.

________________________________

**Comment by BrentOzar** [comment] 2021-04-01 05:53
Gotcha. I'm going to be honest and to the point here: open source doesn't mean free development consulting. If there's a change you want to see in something, and you're the only person experiencing the issue, you're likely going to need to roll up your sleeves and make that change yourself.

I'm going to go ahead and close the issue, but if you change your mind and want to contribute the code in a pull request, we'd love to have it! Check out the contributing guide on how to do that. Thanks anyway!

**Closed by BrentOzar** 2021-04-01 05:53 UTC
Labels: bug, sp_Blitz

**Comment by jvande7471** [comment] 2021-05-11 13:26
We recently had a malware intrusion in our organization.  After a third party analyzed and updated our environment, I started getting this error across our 15 SQL Server instances.  I updated them to the latest sp_blitz and that problem went away.

**Comment by andreasjordan** [comment] 2021-12-01 18:29
I can reproduce this issue and I can reproduce the proposed fix - so I will open a pull request for that.
Some background info: The message "RegOpenKeyEx() returned error 2, 'The system cannot find the file specified.' / Msg 22001, Level 1, State 1" is output because the requested registry key "SOFTWARE\Policies\Microsoft\Power\PowerSettings" is only present when GPOs are used to set the power plan. So this is a "file not found" message. Even if it looks a bit silly, ", @no_output = 'no_output'" append to the end of the call suppresses the message. And yes - this parameter has to be the last parameter in the list. I don't have an idea why order of parameters matter here - but I can live with that question being unanswered...

**Comment by BrentOzar** [comment] 2022-01-08 16:41
Thanks for the pull request. Neato, haven't seen that parameter before! Merging into the dev branch, will be in the next release with credit to you in the release notes.

**Comment by ScottL1969** [comment] 2022-01-09 00:56
andreasjordan, thank you for adding my proposed solution to the code base.
