### ISSUE TITLE
Invalid object name 'DBAtools.dbo.BlitzCache'.

### ISSUE THREAD

**Issue by iwebsguy** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1419] opened 2018-02-09 21:36 UTC
Followed the directions from https://www.brentozar.com/first-aid/first-responder-kit-power-bi-dashboard/

Ran script to isntall SP, created DBAtools DB, ran the query below manually

```
EXEC sp_BlitzFirst 
  @OutputDatabaseName = 'DBAtools', 
  @OutputSchemaName = 'dbo', 
  @OutputTableName = 'BlitzFirst',
  @OutputTableNameFileStats = 'BlitzFirst_FileStats',
  @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
  @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
  @OutputTableNameBlitzCache = 'BlitzCache';
```
The following is output upon first run, running it again does not produce the error.

>  Msg 208, Level 16, State 1, Line 1
> Invalid object name 'DBAtools.dbo.BlitzCache'.

Environment details, also had this same result with SQL 2017.

Microsoft SQL Server 2016 (SP1-CU4) (KB4024305) - 13.0.4446.0 (X64)   Jul 16 2017 18:08:49   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 6.3 <X64> (Build 14393: ) (Hypervisor)

**Comment by BlitzErik** [comment] 2018-02-09 21:46
Please search for issues before filing

Dupe of #1412

**Closed by BlitzErik** 2018-02-09 21:46 UTC
