### ISSUE TITLE
when running sp_BlitzFirst recive error in sp_BlitzCache - Divide by zero

### ISSUE THREAD

**Issue by grawerpl** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1763] opened 2018-09-12 07:42 UTC
i installed Core script without Store Query (newest stable release) and after start this
>EXEC 
> sp_BlitzFirst
>   @ExpertMode = 1,
>   @Seconds = 60,
>   @OutputDatabaseName = 'DBAtools', 
>   @OutputSchemaName = 'dbo', 
>   @OutputTableName = 'BlitzFirst',
>   @OutputTableNameFileStats = 'BlitzFirst_FileStats',
>   @OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
>   @OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
>   @OutputTableNameBlitzCache = 'BlitzCache';
 

i got error:
**Msg 8134, Level 16, State 1, Procedure sp_BlitzCache, Line 3972 [Batch Start Line 0]
Divide by zero error encountered.**

full msg from query:

> Setting up configuration variables
> Warning: The join order has been enforced because a local join hint is used.
> Now starting diagnostic analysis
> Capturing first pass of wait stats, perfmon counters, file stats
> Beginning investigatory queries
> Warning: The join order has been enforced because a local join hint is used.
> Warning: The join order has been enforced because a local join hint is used.
> Finished running investigatory queries
> Waiting to match @Seconds parameter
> Capturing second pass of wait stats, perfmon counters, file stats
> Analyzing changes between first and second passes of DMVs
> Analysis finished, outputting results
> Calling sp_BlitzCache
> Checking @MinutesBack validity.
> Setting @MinutesBack to a negative number
> Creating temp tables for results and warnings.
> Checking database validity
> Checking sort order
> Cleaning up old warnings for your SPID
> Cleaning up old plans for your SPID
> Creating temp tables for internal processing
> Checking plan cache age
> Setting up variables
> Determining SQL Server version.
> Creating dynamic SQL based on SQL Server version.
> Ignoring system databases by default
> Setting minutes back filter
> Applying chosen sort order
> Substituting NULLs for spill columns in older versions of SQL
> Adding additional info columns for newer versions of SQL
> Getting memory grant information for newer versions of SQL
> Substituting NULLs for spill columns in older versions of SQL
> Adding SQL to collect trigger stats.
> Collecting execution plan information.
> Attempting to aggregate stored proc info from separate statements
> Warning: Null value is eliminated by an aggregate or other SET operation.
> Computing CPU, duration, read, and write metrics
> Update CPU percentage for stored procedures
> Gather percentage information from grouped results
> Begin XML nodes processing
> Gathering high level plan information
> Warning: Null value is eliminated by an aggregate or other SET operation.
> Performing query level checks
> Performing compile timeout checks
> Performing compile memory limit exceeded checks
> Gathering trivial plans
> Gathering statement costs
> Updating statement costs
> Gathering stored procedure costs
> Checking for plan warnings
> Checking for implicit conversion
> Performing TVF join check
> Checking for table variables
> Checking for expensive key lookups
> Checking for expensive remote queries
> Checking for expensive sorts
> Checking for Optimistic cursors
> Checking if cursor is Forward Only
> Checking if cursor is Fast Forward
> Checking for Dynamic cursors
> Checking for filters that reference scalar UDFs
> Checking for wonky Index Spools
> Checking for forced serialization
> Gathering additional plan level information
> Warning: Null value is eliminated by an aggregate or other SET operation.
> Attempting to get stored procedure name for individual statements
> Trace flag checks
> Checking for MSTVFs
> Checking for non-sargable predicates
> Getting information about implicit conversions and stored proc parameters
> Getting variable info
> Getting conversion info
> Parsing conversion info
> Updating variables for inserted procs
> Inserting variables for other procs
> Updating procs
> Updating SET options
> Updating conversion XML
> Updating cached parameter XML for stored procs
> Updating cached parameter XML for statements
> Filling in implicit conversion and cached plan parameter info
> Inserting to #missing_index_xml
> Inserting to #missing_index_schema
> Inserting to #missing_index_usage
> Inserting to #missing_index_detail
> Inserting to missing indexes to #missing_index_pretty
> Inserting to #index_spool_ugly
> Inserting to spools to #missing_index_pretty
> Updating missing index information
> Filling in missing index blanks
> Setting configuration values
> Checking for query level SQL Server issues.
> Checking for forced parameterization and cursors.
> Populating Warnings column
> Msg 8134, Level 16, State 1, Procedure sp_BlitzCache, Line 3972 [Batch Start Line 0]
> Divide by zero error encountered.
> The statement has been terminated.
> Populating Warnings column for stored procedures
> Checking for plans with >128 levels of nesting
> Checking for plans with no warnings
> Writing results to table.
> sp_BlitzCache Finished
> Warning: The join order has been enforced because a local join hint is used.

**Comment by grawerpl** [comment] 2018-09-12 08:05
ooo and i forget to mention. SQL Server 2012 SP4

**Comment by RichBenner** [comment] 2018-09-12 09:42
just a quick check, have you tried the latest version of the scripts? there was a bug in the initial release this month that caused a div/0 error.

**Comment by BlitzErik** [comment] 2018-09-12 11:39
Thanks, but this is a duplicate of #1747

Please search issues before posting.

**Closed by BlitzErik** 2018-09-12 11:39 UTC
