### ISSUE TITLE
Power BI - unable to open document

### ISSUE THREAD

**Issue by xkomandosx** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2256] opened 2020-01-16 10:15 UTC
I can't open First Responder Kit.pbix
I have error: Unable to open document - many-to-many or composite model
![image](https://user-images.githubusercontent.com/26285095/72516388-de38eb00-3851-11ea-969c-f37fa63c39a5.png)

I have Power BI (may 2019) on one machine, and on second one I have Power BI (september 2019) = same error.

Could you upgrade file to newest version PBI?

**Comment by EmanueleMeazzo** [comment] 2020-01-16 15:38
I can't reproduce the issue with PowerBi December 2019 and the file in this github; try to update PowerBi and/or download the file again
Regardless, the report is deprecated as of now

**Comment by xkomandosx** [comment] 2020-01-17 09:35
It's work fine on PowerBI December 2019,
I must upgrade Power BI Report Server too.

PS. Microsoft promise to 5 version back compability - :(

**Comment by BrentOzar** [comment] 2020-01-18 12:16
Yeah, we mentioned a couple/few months ago in the release notes that the minimum Power BI Desktop version was August 2019. Closing. Thanks!

**Closed by BrentOzar** 2020-01-18 12:16 UTC
