### ISSUE TITLE
Invalid column name when running sp_blitzcache on SQLServer 2008 R2

### ISSUE THREAD

**Issue by msurasky** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1400] opened 2018-01-24 16:36 UTC
Hi All,

I'm using the latest and greatest sp_blitzcache. There is nothing special or odd about my implementation other than I'm not hosting the First Responder Kit on master (which AFAIK is not a requirement).

How to reproduce? 
I used this exact statement to call sp_blitzcache
sp_blitzcache @SortOrder='CPU', @OutputDatabaseName='[my_company_db_here_which_I_will_not_disclose_to_avoid_getting_into_problems]', @OutputSchemaName='dbo', @OutputTableName='BlitzCache_CPU'

**What is the expected behavior?**
For this to work maybe? pretty please?

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
This worked in the past (at before Dec 2017, which is when this blitzcache started with other unrelated bug)

My @@version says:
Microsoft SQL Server 2008 R2 (SP3) - 10.50.6000.34 (X64) 
	Aug 19 2014 12:21:34 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )

Granted, my server is not running the last hotfix, but it is a PROD environment and it is running the latest service pack so it is not thaaaaaat bad (I don't control when/why this box get patched so I hope this is not a problem caused by my box not having any post sp3 hotfixes, otherwise I won't be able to keep using sp_blitzcache for the time being).

![image](https://user-images.githubusercontent.com/25614072/35344050-c4589b66-00f1-11e8-8465-298eb84f6433.png)

Thanks!

**Comment by BlitzErik** [comment] 2018-01-24 16:38
Duplicate of #1384

**Closed by BlitzErik** 2018-01-24 16:38 UTC
