### ISSUE TITLE
sp_BlitzCache still failing sometimes when executed on instances with readable secondary replicas

### ISSUE THREAD

**Issue by mbambion** [BrentOzarULTD/SQL-Server-First-Responder-Kit#3291] opened 2023-06-26 23:02 UTC
**Version of the script**
Version: 8.14; VersionDate: 20230420
**What is the current behavior?**
We are using sp_BlitzCache to capture top queries on a periodic basis. On execution, sometimes it would fail with the following error:
`Msg 978, Level 14, State 1, Line 15
The target database ('**********') is in an availability group and is currently accessible for connections when the application intent is set to read only. For more information about application intent, see SQL Server Books Online.`

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm using the following script to execute against our Read-Only instance via a SQL Agent job:
```
DECLARE @CheckDateOverride DATETIMEOFFSET = SYSUTCDATETIME()
EXEC sp_BlitzCache
   @Top = 25,
   @SortOrder = 'all',
   @QueryFilter = 'statements',
   @MinutesBack = 15,
   @HideSummary = 1,
   @SkipAnalysis = 1,       /* Skipping analysis to save resources */
   @CheckDateOverride = @CheckDateOverride,
   @OutputDatabaseName = 'DBA', @OutputSchemaName = 'snapshot', @OutputTableName = 'BlitzTopQueries'
```

**What is the expected behavior?**
Job is expected to complete ignoring readable secondaries.
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Version: 13.0.5888.11. Patch Level: SP2. Cumulative Update: CU17. Edition: Enterprise Edition: Core-based Licensing (64-bit). 
I've tested in previous versions and it hasn't worked. 

I did some troubleshooting and it seems what's triggering this is that the DB with ID 32767 is not being ignored, neither as SystemDB or ReadableDB. I can have a look and raise a PR soon. Would be good if you could confirm this bug on your side.

**Comment by BrentOzar** [comment] 2023-06-26 23:04
I can't confirm it on my side because I don't have an AG. You're welcome to submit a pull request though. Thanks!---Tiny glass keyboardTypos flowing like riversAs winter snow thawsOn Jun 26, 2023, at 4:03 PM, mbambion ***@***.***> wrote:﻿
Version of the script
Version: 8.14; VersionDate: 20230420
What is the current behavior?
We are using sp_BlitzCache to capture top queries on a periodic basis. On execution, sometimes it would fail with the following error:
Msg 978, Level 14, State 1, Line 15 The target database ('**********') is in an availability group and is currently accessible for connections when the application intent is set to read only. For more information about application intent, see SQL Server Books Online.
If the current behavior is a bug, please provide the steps to reproduce.
I'm using the following script to execute against our Read-Only instance via a SQL Agent job:
DECLARE @CheckDateOverride DATETIMEOFFSET = SYSUTCDATETIME()
EXEC sp_BlitzCache
   @Top = 25,
   @SortOrder = 'all',
   @QueryFilter = 'statements',
   @MinutesBack = 15,
   @HideSummary = 1,
   @SkipAnalysis = 1,       /* Skipping analysis to save resources */
   @CheckDateOverride = @CheckDateOverride,
   @OutputDatabaseName = 'DBA', @OutputSchemaName = 'snapshot', @OutputTableName = 'BlitzTopQueries'

What is the expected behavior?
Job is expected to complete ignoring readable secondaries.
Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?
Version: 13.0.5888.11. Patch Level: SP2. Cumulative Update: CU17. Edition: Enterprise Edition: Core-based Licensing (64-bit).
I've tested in previous versions and it hasn't worked.
I did some troubleshooting and it seems what's triggering this is that the DB with ID 32767 is not being ignored, neither as SystemDB or ReadableDB. I can have a look and raise a PR soon. Would be good if you could confirm this bug on your side.

**Comment by mbambion** [comment] 2023-06-29 02:43
Thanks! I've raised a [PR](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/3297) related to this issue. Let me know if more work needs to be done. I've tested it in our environment and has now been deployed in our Live instances. No errors so far.

**Comment by BrentOzar** [comment] 2023-07-06 15:34
Thanks for the pull request. Looks good, merging into the dev branch, will be in the next release with credit to you in the release notes.

**Closed by BrentOzar** 2023-07-06 15:34 UTC
Labels: bug, sp_BlitzCache
