### ISSUE TITLE
sp_BlitzFirst does not use sp_BlitzWho if not running from master database

### ISSUE THREAD

**Issue by ghauan** [BrentOzarULTD/SQL-Server-First-Responder-Kit#718] opened 2017-02-24 09:25 UTC
I think there might be a bug in sp_BlitzFirst.

I have all the First Responder Kit-procedures in a separate maintenance database, not master. When I recently upgraded the solution with the latest release, I noticed that when I run sp_BlitzFirst with @expertMode=1, it no longer displays "what is running right now". I asked about this on [stackexchange ](http://dba.stackexchange.com/questions/164432/statements-currently-running-in-sp-blitzfirst)as well, but seemed no one could answer, so I will report it as a bug. 

To reproduce: Have all your procedures in database other than master. Run exec sp_blitzFirst @ExpertMode=1 .

Expected behavior is that the first and last result set is showing what is running on the instance.

I have this behavior both on SQL Server 2012 and SQL Server 2016.

I have briefly looked into the procedure, and it seems to me that it checks for existence of sp_BlitzWho directly in master database, but tries to run it from the local database. But since it does not exist in master, it will not be run at all.

`
IF @SinceStartup = 0 AND @Seconds > 0 AND @ExpertMode = 1 
    BEGIN
		IF OBJECT_ID('master.dbo.sp_BlitzWho') IS NULL
		BEGIN
			PRINT N'sp_BlitzWho is not installed in the current database_files.  You can get a copy from http://FirstResponderKit.org'
		END
		ELSE
		BEGIN
		    DECLARE @BlitzWho NVARCHAR(MAX) = 'EXEC [dbo].[sp_BlitzWho] @ShowSleepingSPIDs = ' + CONVERT(NVARCHAR(1), @ShowSleepingSPIDs)
			EXEC (@BlitzWho)
		END
    END
`

**Comment by BrentOzar** [comment] 2017-02-24 12:53
Thanks, but closing as duplicate of #703.

**Closed by BrentOzar** 2017-02-24 12:53 UTC
