### ISSUE TITLE
Divide by zero Error in BlitzCache

### ISSUE THREAD

**Issue by WinstonDba** [BrentOzarULTD/SQL-Server-First-Responder-Kit#1766] opened 2018-09-14 15:48 UTC
**BUG** - Latest Version - BlitzCache

Issue when I run BlitzCache in a Job Agent Job and write to a table (may happen elsewhere)
**Version**: SQL Server Version 2008 R2
**OS**: Windows Server 2008

Executed Code:

EXEC master.dbo.sp_BlitzCache 
			@Top = 200, -- int
			@ExpertMode = 1, -- tinyint
			@OutputServerName = N'[SERVER NAME]', -- nvarchar(256)
			@OutputDatabaseName = N'[TABLE NAME]', -- nvarchar(256)
			@OutputSchemaName = N'dbo', -- nvarchar(256)
			@OutputTableName = N'BlitzCache'

**Error Message Out Put**

Checking for query level SQL Server issues.
Checking for forced parameterization and cursors.
Populating Warnings column
Msg 8134, Level 16, State 1, Procedure sp_BlitzCache, Line 3972 [Batch Start Line 0]
Divide by zero error encountered.
The statement has been terminated.
Populating Warnings column for stored procedures
Msg 8134, Level 16, State 1, Procedure sp_BlitzCache, Line 4047 [Batch Start Line 0]
Divide by zero error encountered.
The statement has been terminated.
Checking for plans with >128 levels of nesting
Checking for plans with no warnings
Writing results to table.

**Comment by BlitzErik** [comment] 2018-09-14 15:49
Duplicate of #1747 Please search closed issues before opening new ones.

Thanks!
Erik

**Closed by BlitzErik** 2018-09-14 15:49 UTC
