### ISSUE TITLE
sp_blitz reports arithmetic overflow

### ISSUE THREAD

**Issue by MEhrenmueller** [BrentOzarULTD/SQL-Server-First-Responder-Kit#538] opened 2016-10-17 15:27 UTC
I found a *bug* in sp_blitz.

Running sp_blitz generates the following error:
Msg 8115, Level 16, State 2, Procedure sp_Blitz, Line 469
Arithmetic overflow error converting expression to data type int.

Please correct the statement from

        SELECT @MsSinceWaitsCleared = DATEDIFF(MINUTE, create_date, CURRENT_TIMESTAMP) * 60000
            FROM    sys.databases
            WHERE   name='tempdb';

to

        SELECT 
		@MsSinceWaitsCleared = convert(decimal(38,0), DATEDIFF(MINUTE, create_date, CURRENT_TIMESTAMP)) * 60000
            FROM    sys.databases
            WHERE   name='tempdb';

to add an explicit conversion to solve the problem.

**Comment by BrentOzar** [comment] 2016-10-17 15:28
Duplicate of this issue, already fixed in the dev branch:
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/526

**Closed by BrentOzar** 2016-10-17 15:28 UTC
