### ISSUE TITLE
Lock request time out period exceeded when running sp_blitzFirst with @Seconds and @ExpertMode args

### ISSUE THREAD

**Issue by osudude** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2979] opened 2021-08-17 18:11 UTC
SELECT @Version = '8.05', @VersionDate = '20210725';

EXEC sp_BlitzFirst @Seconds =15, @ExpertMode = 1 
Setting up configuration variables
Checking for Read intent databases to exclude
Now starting diagnostic analysis
Checking for Read intent databases to exclude
Determining SQL Server version.
Capturing first pass of wait stats, perfmon counters, file stats
Beginning investigatory queries
Finished running investigatory queries
Waiting to match @Seconds parameter
Capturing second pass of wait stats, perfmon counters, file stats
Analyzing changes between first and second passes of DMVs
Analysis finished, outputting results
Checking for Read intent databases to exclude
Msg 1222, Level 16, State 56, Line 51
Lock request time out period exceeded.

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2014 (SP2-CU10-GDR) (KB4052725) - 12.0.5571.0 (X64)   Jan 10 2018 15:52:08   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) 

Note, running sp_blitzfirst with no arguments seems to run fine.

**Comment by erikdarlingdata** [comment] 2021-08-18 15:08
Hi, and thanks for stopping by. It's a little unclear what you'd like to happen, here, though.

There's a portion of the code that [sets an intentionally short lock timeout](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/main/sp_BlitzFirst.sql#L2462) to avoid some blocking scenarios that we've run into.

You're more than welcome to change that value to a higher one locally if you're okay waiting longer for that section of code to complete. 

If you were filing this as a bug report because of the error message, you can close it out. This is intended behavior.

**Comment by osudude** [comment] 2021-08-18 16:25
Oh thanks... I didn't realize this was intentional.  Could the message elaborate a little more ("Lock timeout exceeded, see URL XYZ for more info") ?

**Comment by BrentOzar** [comment] 2021-08-18 17:30
That message is generated by SQL Server, not by us. If you can find a way to work around it, though, you're absolutely welcome - that's a pull request we'd absolutely welcome.

**Closed** 2021-08-18 19:06 UTC
