### ISSUE TITLE
sp_BlitzIndex: XML Parse error, not reproducible yet

### ISSUE THREAD

**Issue by fernoca** [BrentOzarULTD/SQL-Server-First-Responder-Kit#2593] opened 2020-09-21 11:42 UTC
**Version of the script**
7.99 - 13th Sept 2020

**What is the current behavior?**
An error is thrown: XML parsing: line 1, character 640, semicolon expected

**If the current behavior is a bug, please provide the steps to reproduce.**
`EXEC dbo.sp_BlitzIndex @DatabaseName = N'WBACDWGB',
@Debug = 1
`

**What is the expected behavior?**
To execute without error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
Microsoft SQL Server 2014 (SP3-CU4) (KB4500181) - 12.0.6329.1 (X64)   Jul 20 2019 21:42:29   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) 

**Full Debug Text**
`Starting run. sp_BlitzIndex(TM) v7.99 - September 13, 2020
Create temp tables.
Adding UQ index on #IndexSanity (database_id, object_id, index_id)
Number of databases to examine: 1
Checking partition counts to exclude databases with over 100 partitions
Starting loop through databases

WBACDWGB
Inserting data into #IndexColumns for clustered indexes and heaps
/* sp_BlitzIndex */
				SET LOCK_TIMEOUT 1000; /* To fix locking bug in sys.identity_columns. See Github issue #2176. */
				SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
                SELECT 37,
					s.name,    
                    si.object_id, 
                    si.index_id, 
                    sc.key_ordinal, 
                    sc.is_included_column, 
                    sc.is_descending_key,
                    sc.partition_ordinal,
                    c.name as column_name, 
                    st.name as system_type_name,
                    c.max_length,
                    c.[precision],
                    c.[scale],
                    c.collation_name,
                    c.is_nullable,
                    c.is_identity,
                    c.is_computed,
                    c.is_replicated,
                    c.is_sparse,
                    c.is_filestream,
                    CAST(ic.seed_value AS DECIMAL(38,0)),
                    CAST(ic.increment_value AS DECIMAL(38,0)),
                    CAST(ic.last_value AS DECIMAL(38,0)),
                    ic.is_not_for_replication
                FROM    [WBACDWGB].sys.indexes si
                JOIN    [WBACDWGB].sys.columns c ON
                    si.object_id=c.object_id
                LEFT JOIN [WBACDWGB].sys.index_columns sc ON 
                    sc.object_id = si.object_id
                    and sc.index_id=si.index_id
                    AND sc.column_id=c.column_id
                LEFT JOIN [WBACDWGB].sys.identity_columns ic ON
                    c.object_id=ic.object_id and
                    c.column_id=ic.column_id
                JOIN [WBACDWGB].sys.types st ON 
                    c.system_type_id=st.system_type_id
                    AND c.user_type_id=st.user_type_id
				JOIN [WBACDWGB].sys.objects AS so  ON si.object_id = so.object_id
																		  AND so.is_ms_shipped = 0
				JOIN [WBACDWGB].sys.schemas AS s ON s.schema_id = so.schema_id
                WHERE si.index_id in (0,1) OPTION (RECOMPILE);
 
 
 
 
 
 
 
 
 
Inserting data into #IndexColumns for nonclustered indexes
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
                SELECT 37, 
					s.name,    
                    si.object_id, 
                    si.index_id, 
                    sc.key_ordinal, 
                    sc.is_included_column, 
                    sc.is_descending_key,
                    sc.partition_ordinal,
                    c.name as column_name, 
                    st.name as system_type_name,
                    c.max_length,
                    c.[precision],
                    c.[scale],
                    c.collation_name,
                    c.is_nullable,
                    c.is_identity,
                    c.is_computed,
                    c.is_replicated,
                    c.is_sparse,
                    c.is_filestream                
                FROM    [WBACDWGB].sys.indexes AS si
                JOIN    [WBACDWGB].sys.columns AS c ON
                    si.object_id=c.object_id
                JOIN [WBACDWGB].sys.index_columns AS sc ON 
                    sc.object_id = si.object_id
                    and sc.index_id=si.index_id
                    AND sc.column_id=c.column_id
                JOIN [WBACDWGB].sys.types AS st ON 
                    c.system_type_id=st.system_type_id
                    AND c.user_type_id=st.user_type_id
				JOIN [WBACDWGB].sys.objects AS so  ON si.object_id = so.object_id
																		  AND so.is_ms_shipped = 0
				JOIN [WBACDWGB].sys.schemas AS s ON s.schema_id = so.schema_id
                WHERE si.index_id not in (0,1) OPTION (RECOMPILE);
 
 
 
 
 
 
 
 
 
Inserting data into #IndexSanity
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
                SELECT  37 AS database_id, 
                        so.object_id, 
                        si.index_id, 
                        si.type,
                        @i_DatabaseName AS database_name, 
                        COALESCE(sc.NAME, 'Unknown') AS [schema_name],
                        COALESCE(so.name, 'Unknown') AS [object_name], 
                        COALESCE(si.name, 'Unknown') AS [index_name],
                        CASE    WHEN so.[type] = CAST('V' AS CHAR(2)) THEN 1 ELSE 0 END, 
                        si.is_unique, 
                        si.is_primary_key, 
                        CASE when si.type = 3 THEN 1 ELSE 0 END AS is_XML,
                        CASE when si.type = 4 THEN 1 ELSE 0 END AS is_spatial,
                        CASE when si.type = 6 THEN 1 ELSE 0 END AS is_NC_columnstore,
                        CASE when si.type = 5 then 1 else 0 end as is_CX_columnstore,
                        CASE when si.data_space_id = 0 then 1 else 0 end as is_in_memory_oltp,
                        si.is_disabled,
                        si.is_hypothetical, 
                        si.is_padded, 
                        si.fill_factor,
                        CASE WHEN si.filter_definition IS NOT NULL THEN si.filter_definition
                             ELSE N''
                        END AS filter_definition
                        , ISNULL(us.user_seeks, 0),
                        ISNULL(us.user_scans, 0),
                        ISNULL(us.user_lookups, 0),
                        ISNULL(us.user_updates, 0),
                        us.last_user_seek,
                        us.last_user_scan,
                        us.last_user_lookup,
                        us.last_user_update,
                        so.create_date,
                        so.modify_date
                FROM    [WBACDWGB].sys.indexes AS si WITH (NOLOCK)
                        JOIN [WBACDWGB].sys.objects AS so WITH (NOLOCK) ON si.object_id = so.object_id
                                               AND so.is_ms_shipped = 0 /*Exclude objects shipped by Microsoft*/
                                               AND so.type <> 'TF' /*Exclude table valued functions*/
                        JOIN [WBACDWGB].sys.schemas sc ON so.schema_id = sc.schema_id
                        LEFT JOIN sys.dm_db_index_usage_stats AS us WITH (NOLOCK) ON si.[object_id] = us.[object_id]
                                                                       AND si.index_id = us.index_id
                                                                       AND us.database_id = 37
                WHERE    si.[type] IN ( 0, 1, 2, 3, 4, 5, 6 ) 
                /* Heaps, clustered, nonclustered, XML, spatial, Cluster Columnstore, NC Columnstore */ AND ( us.user_seeks + us.user_scans + us.user_lookups + us.user_updates ) > 0OPTION    ( RECOMPILE );
        
 
 
 
 
 
 
 
 
 
Checking partition count
Preferring non-2012 syntax with LEFT JOIN to sys.dm_db_index_operational_stats
Inserting data into #IndexPartitionSanity
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
                        SELECT  37 AS database_id,
                                ps.object_id, 
								s.name,
                                ps.index_id, 
                                ps.partition_number, 
                                ps.row_count,
                                ps.reserved_page_count * 8. / 1024. AS reserved_MB,
                                ps.lob_reserved_page_count * 8. / 1024. AS reserved_LOB_MB,
                                ps.row_overflow_reserved_page_count * 8. / 1024. AS reserved_row_overflow_MB,
								le.lock_escalation_desc,
                            par.data_compression_desc ,
                                SUM(os.leaf_insert_count), 
                                SUM(os.leaf_delete_count), 
                                SUM(os.leaf_update_count), 
                                SUM(os.range_scan_count), 
                                SUM(os.singleton_lookup_count),  
                                SUM(os.forwarded_fetch_count),
                                SUM(os.lob_fetch_in_pages), 
                                SUM(os.lob_fetch_in_bytes), 
                                SUM(os.row_overflow_fetch_in_pages),
                                SUM(os.row_overflow_fetch_in_bytes), 
                                SUM(os.row_lock_count), 
                                SUM(os.row_lock_wait_count),
                                SUM(os.row_lock_wait_in_ms), 
                                SUM(os.page_lock_count), 
                                SUM(os.page_lock_wait_count), 
                                SUM(os.page_lock_wait_in_ms),
                                SUM(os.index_lock_promotion_attempt_count), 
                                SUM(os.index_lock_promotion_count), 
								SUM(os.page_latch_wait_count),
								SUM(os.page_latch_wait_in_ms),
								SUM(os.page_io_latch_wait_count),								
								SUM(os.page_io_latch_wait_in_ms)
                    FROM    [WBACDWGB].sys.dm_db_partition_stats AS ps  
                    JOIN [WBACDWGB].sys.partitions AS par on ps.partition_id=par.partition_id
                    JOIN [WBACDWGB].sys.objects AS so ON ps.object_id = so.object_id
                               AND so.is_ms_shipped = 0 /*Exclude objects shipped by Microsoft*/
                               AND so.type <> 'TF' /*Exclude table valued functions*/
					JOIN [WBACDWGB].sys.schemas AS s ON s.schema_id = so.schema_id
                    LEFT JOIN [WBACDWGB].sys.dm_db_index_operational_stats(37, NULL, NULL,NULL) AS os ON
                    ps.object_id=os.object_id and ps.index_id=os.index_id and ps.partition_number=os.partition_number 
			            OUTER APPLY (SELECT st.lock_escalation_desc
			                         FROM [WBACDWGB].sys.tables st
			                         WHERE st.object_id = ps.object_id
			                             AND ps.index_id < 2 ) le
                    WHERE 1=1 
                     
                     
            GROUP BY ps.object_id, 
								s.name,
                                ps.index_id, 
                                ps.partition_number, 
                                ps.row_count,
                                ps.reserved_page_count,
                                ps.lob_reserved_page_count,
                                ps.row_overflow_reserved_page_count,
								le.lock_escalation_desc,
                            par.data_compression_desc 
			ORDER BY ps.object_id,  ps.index_id, ps.partition_number
            OPTION    ( RECOMPILE );
            
 
 
 
 
 
 
 
 
 
Warning: Null value is eliminated by an aggregate or other SET operation.
Inserting data into #MissingIndexes
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;WITH ColumnNamesWithDataTypes AS(SELECT id.index_handle,id.object_id,cn.IndexColumnType,STUFF((SELECT ', ' + cn_inner.ColumnName + ' ' +
			N' {' + CASE	 WHEN ty.name IN ( 'varchar', 'char' ) THEN ty.name + '(' + CASE WHEN co.max_length = -1 THEN 'max' ELSE CAST(co.max_length AS VARCHAR(25)) END + ')'
								WHEN ty.name IN ( 'nvarchar', 'nchar' ) THEN ty.name + '(' + CASE WHEN co.max_length = -1 THEN 'max' ELSE CAST(co.max_length / 2 AS VARCHAR(25)) END + ')'
								WHEN ty.name IN ( 'decimal', 'numeric' ) THEN ty.name + '(' + CAST(co.precision AS VARCHAR(25)) + ', ' + CAST(co.scale AS VARCHAR(25)) + ')'
								WHEN ty.name IN ( 'datetime2' ) THEN ty.name + '(' + CAST(co.scale AS VARCHAR(25)) + ')'
								ELSE ty.name END + '}'
				FROM	sys.dm_db_missing_index_details AS id_inner
				CROSS APPLY(
					SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Equality' AS IndexColumnType
					FROM	(VALUES (CONVERT(XML, N'<x>' + REPLACE(CAST(id_inner.equality_columns AS nvarchar(max)), N',', N'</x><x>') + N'</x>'))) x(n)
					CROSS APPLY n.nodes('x') node(v)
				UNION ALL
					SELECT	LTRIM(RTRIM(v.value(N'(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Inequality' AS IndexColumnType
					FROM	(VALUES (CONVERT(XML, N'<x>' + REPLACE(CAST(id_inner.inequality_columns AS nvarchar(max)), N',', N'</x><x>') + N'</x>'))) x(n)
					CROSS APPLY n.nodes('x') node(v)
				UNION ALL
					SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Included' AS IndexColumnType
					FROM	(VALUES (CONVERT(XML, N'<x>' + REPLACE(CAST(id_inner.included_columns AS nvarchar(max)), N',', N'</x><x>') + N'</x>'))) x(n)
					CROSS APPLY n.nodes('x') node(v)
			)AS cn_inner		JOIN	[WBACDWGB].sys.columns AS co ON co.object_id = id_inner.object_id AND '[' + co.name + ']' = cn_inner.ColumnName
				JOIN	[WBACDWGB].sys.types AS ty ON ty.user_type_id = co.user_type_id 
                WHERE id_inner.index_handle = id.index_handle
				AND	id_inner.object_id = id.object_id
				AND cn_inner.IndexColumnType = cn.IndexColumnType
				FOR XML PATH('')
			 ),1,1,'') AS ReplaceColumnNames
            FROM sys.dm_db_missing_index_details AS id
           CROSS APPLY(
						SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Equality' AS IndexColumnType
						FROM	(VALUES (CONVERT(XML, N'<x>' + REPLACE(CAST(id.equality_columns AS nvarchar(max)), N',', N'</x><x>') + N'</x>'))) x(n)
						CROSS APPLY n.nodes('x') node(v)
				    UNION ALL
						SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Inequality' AS IndexColumnType
						FROM	(VALUES (CONVERT(XML, N'<x>' + REPLACE(CAST(id.inequality_columns AS nvarchar(max)), N',', N'</x><x>') + N'</x>'))) x(n)
						CROSS APPLY n.nodes('x') node(v)
				    UNION ALL
						SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Included' AS IndexColumnType
						FROM	(VALUES (CONVERT(XML, N'<x>' + REPLACE(CAST(id.included_columns AS nvarchar(max)), N',', N'</x><x>') + N'</x>'))) x(n)
						CROSS APPLY n.nodes('x') node(v)
					)AS cn
				GROUP BY	id.index_handle,id.object_id,cn.IndexColumnType
				)
                SELECT  id.database_id, id.object_id, @i_DatabaseName, sc.[name], so.[name], id.statement , gs.avg_total_user_cost, 
                        gs.avg_user_impact, gs.user_seeks, gs.user_scans, gs.unique_compiles, id.equality_columns, id.inequality_columns, id.included_columns,
				(
                    SELECT ColumnNamesWithDataTypes.ReplaceColumnNames 
                    FROM ColumnNamesWithDataTypes WHERE ColumnNamesWithDataTypes.index_handle = id.index_handle
                    AND ColumnNamesWithDataTypes.object_id = id.object_id
                    AND ColumnNamesWithDataTypes.IndexColumnType = 'Equality'
                ) AS equality_columns_with_data_type
                ,(
                    SELEC
T ColumnNamesWithDataTypes.ReplaceColumnNames 
                    FROM ColumnNamesWithDataTypes WHERE ColumnNamesWithDataTypes.index_handle = id.index_handle
                    AND ColumnNamesWithDataTypes.object_id = id.object_id
                    AND ColumnNamesWithDataTypes.IndexColumnType = 'Inequality'
                ) AS inequality_columns_with_data_type
                ,(
                    SELECT ColumnNamesWithDataTypes.ReplaceColumnNames 
                    FROM ColumnNamesWithDataTypes WHERE ColumnNamesWithDataTypes.index_handle = id.index_handle
                    AND ColumnNamesWithDataTypes.object_id = id.object_id
                    AND ColumnNamesWithDataTypes.IndexColumnType = 'Included'
                ) AS included_columns_with_data_type
                FROM    sys.dm_db_missing_index_groups ig
                        JOIN sys.dm_db_missing_index_details id ON ig.index_handle = id.index_handle
                        JOIN sys.dm_db_missing_index_group_stats gs ON ig.index_group_handle = gs.group_handle
                        JOIN [WBACDWGB].sys.objects so on 
                            id.object_id=so.object_id
                        JOIN [WBACDWGB].sys.schemas sc on 
                            so.schema_id=sc.schema_id
                WHERE    id.database_id = 37
                OPTION (RECOMPILE);
 
 
 
 
 
 
 
 
Failure populating temp tables.
Last @dsql: SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;WITH ColumnNamesWithDataTypes AS(SELECT id.index_handle,id.object_id,cn.IndexColumnType,STUFF((SELECT ', ' + cn_inner.ColumnName + ' ' +
			N' {' + CASE	 WHEN ty.name IN ( 'varchar', 'char' ) THEN ty.name + '(' + CASE WHEN co.max_length = -1 THEN 'max' ELSE CAST(co.max_length AS VARCHAR(25)) END + ')'
								WHEN ty.name IN ( 'nvarchar', 'nchar' ) THEN ty.name + '(' + CASE WHEN co.max_length = -1 THEN 'max' ELSE CAST(co.max_length / 2 AS VARCHAR(25)) END + ')'
								WHEN ty.name IN ( 'decimal', 'numeric' ) THEN ty.name + '(' + CAST(co.precision AS VARCHAR(25)) + ', ' + CAST(co.scale AS VARCHAR(25)) + ')'
								WHEN ty.name IN ( 'datetime2' ) THEN ty.name + '(' + CAST(co.scale AS VARCHAR(25)) + ')'
								ELSE ty.name END + '}'
				FROM	sys.dm_db_missing_index_details AS id_inner
				CROSS APPLY(
					SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Equality' AS IndexColumnType
					FROM	(VALUES (CONVERT(XML, N'<x>' + REPLACE(CAST(id_inner.equality_columns AS nvarchar(max)), N',', N'</x><x>') + N'</x>'))) x(n)
					CROSS APPLY n.nodes('x') node(v)
				UNION ALL
					SELECT	LTRIM(RTRIM(v.value(N'(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Inequality' AS IndexColumnType
					FROM	(VALUES (CONVERT(XML, N'<x>' + REPLACE(CAST(id_inner.inequality_columns AS nvarchar(max)), N',', N'</x><x>') + N'</x>'))) x(n)
					CROSS APPLY n.nodes('x') node(v)
				UNION ALL
					SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Included' AS IndexColumnType
					FROM	(VALUES (CONVERT(XML, N'<x>' + REPLACE(CAST(id_inner.included_columns AS nvarchar(max)), N',', N'</x><x>') + N'</x>'))) x(n)
					CROSS APPLY n.nodes('x') node(v)
			)AS cn_inner		JOIN	[WBACDWGB].sys.columns AS co ON co.object_id = id_inner.object_id AND '[' + co.name + ']' = cn_inner.ColumnName
				JOIN	[WBACDWGB].sys.types AS ty ON ty.user_type_id = co.user_type_id 
                WHERE id_inner.index_handle = id.inde...
Msg 50000, Level 16, State 1, Procedure sp_BlitzIndex, Line 2002 [Batch Start Line 0]
WBACDWGB database failed to process. XML parsing: line 1, character 640, semicolon expected

Completion time: 2020-09-21T12:40:29.2763823+01:00
`

**Comment by ASerebryakovRus** [comment] 2020-10-01 20:13
I'm faced with the same error:
`Inserting data into #IndexColumns for clustered indexes and heaps
Inserting data into #IndexColumns for nonclustered indexes
Inserting data into #IndexSanity
Checking partition count
Preferring non-2012 syntax with LEFT JOIN to sys.dm_db_index_operational_stats
Inserting data into #IndexPartitionSanity
Warning: Null value is eliminated by an aggregate or other SET operation.
Inserting data into #MissingIndexes
Failure populating temp tables.
Last @dsql: SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;WITH ColumnNamesWithDataTypes AS(SELECT id.index_handle,id.object_id,cn.IndexColumnType,STUFF((SELECT cn_inner.ColumnName + ' ' +
					N' {' + CASE	 WHEN ty.name IN ( 'varchar', 'char' ) THEN ty.name + '(' + CASE WHEN co.max_length = -1 THEN 'max' ELSE CAST(co.max_length AS VARCHAR(25)) END + ')'
								WHEN ty.name IN ( 'nvarchar', 'nchar' ) THEN ty.name + '(' + CASE WHEN co.max_length = -1 THEN 'max' ELSE CAST(co.max_length / 2 AS VARCHAR(25)) END + ')'
								WHEN ty.name IN ( 'decimal', 'numeric' ) THEN ty.name + '(' + CAST(co.precision AS VARCHAR(25)) + ', ' + CAST(co.scale AS VARCHAR(25)) + ')'
								WHEN ty.name IN ( 'datetime2' ) THEN ty.name + '(' + CAST(co.scale AS VARCHAR(25)) + ')'
								ELSE ty.name END + '} '
				FROM	sys.dm_db_missing_index_details AS id_inner
				CROSS APPLY(
					SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Equality' AS IndexColumnType
					FROM	(VALUES (CONVERT(XML, '<x>' + REPLACE(id_inner.equality_columns, ',', '</x><x>')+'</x>'))) x(n)
					CROSS APPLY n.nodes('x') node(v)
				UNION ALL
					SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Inequality' AS IndexColumnType
					FROM	(VALUES (CONVERT(XML, '<x>' + REPLACE(id_inner.inequality_columns, ',', '</x><x>')+'</x>'))) x(n)
					CROSS APPLY n.nodes('x') node(v)
				UNION ALL
					SELECT	LTRIM(RTRIM(v.value('(./text())[1]', 'varchar(max)'))) AS ColumnName, 'Included' AS IndexColumnType
					FROM	(VALUES (CONVERT(XML, '<x>' + REPLACE(id_inner.included_columns, ',', '</x><x>')+'</x>'))) x(n)
					CROSS APPLY n.nodes('x') node(v)
			)AS cn_inner		JOIN	[STAGING].sys.columns AS co ON co.object_id = id_inner.object_id AND '[' + co.name + ']' = cn_inner.ColumnName
				JOIN	[STAGING].sys.types AS ty ON ty.user_type_id = co.user_type_id 
                WHERE id_inner.index_handle = id.index_handle
				AND	id_inner.object_id = id.object_id
				AND cn_inner.IndexColumnType = cn.Ind...
Msg 50000, Level 16, State 1, Procedure sp_BlitzIndex, Line 1980 [Batch Start Line 0]
XYZ database failed to process. XML parsing: line 1, character 32, semicolon expected`

**Comment by BrentOzar** [comment] 2020-10-10 12:17
I'm in a tough spot: it's working fine for me here (and at every client I have), so I can't really tell what's inside your database that's triggering this issue.

You'll need to dig deeper to take the dynamic SQL shown on the Messages tab when Debug = 1 is turned on, try running that code, and track down what feature, index name, etc is causing the issue.

Let me know if there's anything specific you need from me in order to help, but unfortunately this just isn't something I can troubleshoot remotely.

**Comment by erikdarlingdata** [comment] 2020-10-11 17:14
This is almost certainly because there's an odd character in in a table name or something. For example, it's a transient issue in [sp_WhoIsActive](https://github.com/amachanic/sp_whoisactive/issues/9) as well. It's probably some mix of characters and collations.

**Comment by BrentOzar** [comment] 2020-10-15 12:36
@ASerebryakovRus and @fernoca - when you can reproduce it and identify what's causing the issue, leave a note here and I can reopen the issue - otherwise closing for now. Thanks!

**Closed by BrentOzar** 2020-10-15 12:36 UTC
Labels: bug, sp_BlitzIndex

**Comment by snaphooks** [comment] 2021-01-21 18:09
I'm having the same issue.  I will look for odd characters as erik suggests:

Msg 9411, Level 16, State 1, Line 5
XML parsing: line 1, character 775, semicolon expected

Completion time: 2021-01-21T10:06:16.0991145-08:00

**Comment by snaphooks** [comment] 2021-01-29 19:03
I found the problem, I think.  We had a field with a ">" in the name.  WHen i debugged and removed that object_id from the results it works fine.  I will either rename the field or alter the sp_blitzindex code to ignore that object_id.
